//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Organizations.HelperClasses;
using RoomManagerment.Organizations.FactoryClasses;
using RoomManagerment.Organizations.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Organizations.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'OrganizationBanking'.<br/><br/></summary>
	[Serializable]
	public partial class OrganizationBankingEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private OrganizationEntity _organization;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static OrganizationBankingEntityStaticMetaData _staticMetaData = new OrganizationBankingEntityStaticMetaData();
		private static OrganizationBankingRelations _relationsFactory = new OrganizationBankingRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Organization</summary>
			public static readonly string Organization = "Organization";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OrganizationBankingEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OrganizationBankingEntityStaticMetaData()
			{
				SetEntityCoreInfo("OrganizationBankingEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Organizations.EntityType.OrganizationBankingEntity, typeof(OrganizationBankingEntity), typeof(OrganizationBankingEntityFactory), false);
				AddNavigatorMetaData<OrganizationBankingEntity, OrganizationEntity>("Organization", "OrganizationBankings", (a, b) => a._organization = b, a => a._organization, (a, b) => a.Organization = b, RoomManagerment.Organizations.RelationClasses.StaticOrganizationBankingRelations.OrganizationEntityUsingOrganizationIdStatic, ()=>new OrganizationBankingRelations().OrganizationEntityUsingOrganizationId, null, new int[] { (int)OrganizationBankingFieldIndex.OrganizationId }, null, true, (int)RoomManagerment.Organizations.EntityType.OrganizationEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static OrganizationBankingEntity()
		{
		}

		/// <summary> CTor</summary>
		public OrganizationBankingEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OrganizationBankingEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OrganizationBankingEntity</param>
		public OrganizationBankingEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for OrganizationBanking which data should be fetched into this OrganizationBanking object</param>
		public OrganizationBankingEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for OrganizationBanking which data should be fetched into this OrganizationBanking object</param>
		/// <param name="validator">The custom validator object for this OrganizationBankingEntity</param>
		public OrganizationBankingEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OrganizationBankingEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Organization' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrganization() { return CreateRelationInfoForNavigator("Organization"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OrganizationBankingEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OrganizationBankingRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Organization' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrganization { get { return _staticMetaData.GetPrefetchPathElement("Organization", CommonEntityBase.CreateEntityCollection<OrganizationEntity>()); } }

		/// <summary>The AccountHolderName property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."account_holder_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String AccountHolderName
		{
			get { return (System.String)GetValue((int)OrganizationBankingFieldIndex.AccountHolderName, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.AccountHolderName, value); }
		}

		/// <summary>The AccountNumber property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."account_number".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String AccountNumber
		{
			get { return (System.String)GetValue((int)OrganizationBankingFieldIndex.AccountNumber, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.AccountNumber, value); }
		}

		/// <summary>The BranchCode property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."branch_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String BranchCode
		{
			get { return (System.String)GetValue((int)OrganizationBankingFieldIndex.BranchCode, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.BranchCode, value); }
		}

		/// <summary>The BranchName property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."branch_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String BranchName
		{
			get { return (System.String)GetValue((int)OrganizationBankingFieldIndex.BranchName, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.BranchName, value); }
		}

		/// <summary>The CreatedAt property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)OrganizationBankingFieldIndex.CreatedAt, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DeletedAt property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OrganizationBankingFieldIndex.DeletedAt, false); }
			set { SetValue((int)OrganizationBankingFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)OrganizationBankingFieldIndex.DeletedBy, false); }
			set { SetValue((int)OrganizationBankingFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Id property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)OrganizationBankingFieldIndex.Id, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.Id, value); }
		}

		/// <summary>The IsPrimary property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."is_primary".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsPrimary
		{
			get { return (System.Boolean)GetValue((int)OrganizationBankingFieldIndex.IsPrimary, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.IsPrimary, value); }
		}

		/// <summary>The OrganizationId property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."organization_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid OrganizationId
		{
			get { return (System.Guid)GetValue((int)OrganizationBankingFieldIndex.OrganizationId, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.OrganizationId, value); }
		}

		/// <summary>The SepayBankId property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."sepay_bank_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> SepayBankId
		{
			get { return (Nullable<System.Guid>)GetValue((int)OrganizationBankingFieldIndex.SepayBankId, false); }
			set { SetValue((int)OrganizationBankingFieldIndex.SepayBankId, value); }
		}

		/// <summary>The SwiftCode property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."swift_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 30.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SwiftCode
		{
			get { return (System.String)GetValue((int)OrganizationBankingFieldIndex.SwiftCode, true); }
			set { SetValue((int)OrganizationBankingFieldIndex.SwiftCode, value); }
		}

		/// <summary>The UpdatedAt property of the Entity OrganizationBanking<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organization_banking"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OrganizationBankingFieldIndex.UpdatedAt, false); }
			set { SetValue((int)OrganizationBankingFieldIndex.UpdatedAt, value); }
		}

		/// <summary>Gets / sets related entity of type 'OrganizationEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrganizationEntity Organization
		{
			get { return _organization; }
			set { SetSingleRelatedEntityNavigator(value, "Organization"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Organizations
{
	public enum OrganizationBankingFieldIndex
	{
		///<summary>AccountHolderName. </summary>
		AccountHolderName,
		///<summary>AccountNumber. </summary>
		AccountNumber,
		///<summary>BranchCode. </summary>
		BranchCode,
		///<summary>BranchName. </summary>
		BranchName,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Id. </summary>
		Id,
		///<summary>IsPrimary. </summary>
		IsPrimary,
		///<summary>OrganizationId. </summary>
		OrganizationId,
		///<summary>SepayBankId. </summary>
		SepayBankId,
		///<summary>SwiftCode. </summary>
		SwiftCode,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Organizations.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: OrganizationBanking. </summary>
	public partial class OrganizationBankingRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between OrganizationBankingEntity and OrganizationEntity over the m:1 relation they have, using the relation between the fields: OrganizationBanking.OrganizationId - Organization.Id</summary>
		public virtual IEntityRelation OrganizationEntityUsingOrganizationId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Organization", false, new[] { OrganizationFields.Id, OrganizationBankingFields.OrganizationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOrganizationBankingRelations
	{
		internal static readonly IEntityRelation OrganizationEntityUsingOrganizationIdStatic = new OrganizationBankingRelations().OrganizationEntityUsingOrganizationId;

		/// <summary>CTor</summary>
		static StaticOrganizationBankingRelations() { }
	}
}
