//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Organizations.HelperClasses;
using RoomManagerment.Organizations.FactoryClasses;
using RoomManagerment.Organizations.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Organizations.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Organization'.<br/><br/></summary>
	[Serializable]
	public partial class OrganizationEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<OrganizationBankingEntity> _organizationBankings;
		private EntityCollection<OrganizationUserEntity> _organizationUsers;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static OrganizationEntityStaticMetaData _staticMetaData = new OrganizationEntityStaticMetaData();
		private static OrganizationRelations _relationsFactory = new OrganizationRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name OrganizationBankings</summary>
			public static readonly string OrganizationBankings = "OrganizationBankings";
			/// <summary>Member name OrganizationUsers</summary>
			public static readonly string OrganizationUsers = "OrganizationUsers";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OrganizationEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OrganizationEntityStaticMetaData()
			{
				SetEntityCoreInfo("OrganizationEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Organizations.EntityType.OrganizationEntity, typeof(OrganizationEntity), typeof(OrganizationEntityFactory), false);
				AddNavigatorMetaData<OrganizationEntity, EntityCollection<OrganizationBankingEntity>>("OrganizationBankings", a => a._organizationBankings, (a, b) => a._organizationBankings = b, a => a.OrganizationBankings, () => new OrganizationRelations().OrganizationBankingEntityUsingOrganizationId, typeof(OrganizationBankingEntity), (int)RoomManagerment.Organizations.EntityType.OrganizationBankingEntity);
				AddNavigatorMetaData<OrganizationEntity, EntityCollection<OrganizationUserEntity>>("OrganizationUsers", a => a._organizationUsers, (a, b) => a._organizationUsers = b, a => a.OrganizationUsers, () => new OrganizationRelations().OrganizationUserEntityUsingOrganizationId, typeof(OrganizationUserEntity), (int)RoomManagerment.Organizations.EntityType.OrganizationUserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static OrganizationEntity()
		{
		}

		/// <summary> CTor</summary>
		public OrganizationEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OrganizationEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OrganizationEntity</param>
		public OrganizationEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Organization which data should be fetched into this Organization object</param>
		public OrganizationEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Organization which data should be fetched into this Organization object</param>
		/// <param name="validator">The custom validator object for this OrganizationEntity</param>
		public OrganizationEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OrganizationEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrganizationBanking' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrganizationBankings() { return CreateRelationInfoForNavigator("OrganizationBankings"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrganizationUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrganizationUsers() { return CreateRelationInfoForNavigator("OrganizationUsers"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OrganizationEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OrganizationRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrganizationBanking' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrganizationBankings { get { return _staticMetaData.GetPrefetchPathElement("OrganizationBankings", CommonEntityBase.CreateEntityCollection<OrganizationBankingEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrganizationUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrganizationUsers { get { return _staticMetaData.GetPrefetchPathElement("OrganizationUsers", CommonEntityBase.CreateEntityCollection<OrganizationUserEntity>()); } }

		/// <summary>The Address property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."address".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Address
		{
			get { return (System.String)GetValue((int)OrganizationFieldIndex.Address, true); }
			set { SetValue((int)OrganizationFieldIndex.Address, value); }
		}

		/// <summary>The Code property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)OrganizationFieldIndex.Code, true); }
			set { SetValue((int)OrganizationFieldIndex.Code, value); }
		}

		/// <summary>The CreatedAt property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)OrganizationFieldIndex.CreatedAt, true); }
			set { SetValue((int)OrganizationFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DeletedAt property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OrganizationFieldIndex.DeletedAt, false); }
			set { SetValue((int)OrganizationFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)OrganizationFieldIndex.DeletedBy, false); }
			set { SetValue((int)OrganizationFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Email property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."email".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Email
		{
			get { return (System.String)GetValue((int)OrganizationFieldIndex.Email, true); }
			set { SetValue((int)OrganizationFieldIndex.Email, value); }
		}

		/// <summary>The FirstTrialAt property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."first_trial_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> FirstTrialAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OrganizationFieldIndex.FirstTrialAt, false); }
			set { SetValue((int)OrganizationFieldIndex.FirstTrialAt, value); }
		}

		/// <summary>The HasEverPaid property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."has_ever_paid".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean HasEverPaid
		{
			get { return (System.Boolean)GetValue((int)OrganizationFieldIndex.HasEverPaid, true); }
			set { SetValue((int)OrganizationFieldIndex.HasEverPaid, value); }
		}

		/// <summary>The Id property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)OrganizationFieldIndex.Id, true); }
			set { SetValue((int)OrganizationFieldIndex.Id, value); }
		}

		/// <summary>The Mail property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."mail".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Mail
		{
			get { return (System.String)GetValue((int)OrganizationFieldIndex.Mail, true); }
			set { SetValue((int)OrganizationFieldIndex.Mail, value); }
		}

		/// <summary>The Name property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)OrganizationFieldIndex.Name, true); }
			set { SetValue((int)OrganizationFieldIndex.Name, value); }
		}

		/// <summary>The PaidSubscriptionsCount property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."paid_subscriptions_count".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 PaidSubscriptionsCount
		{
			get { return (System.Int32)GetValue((int)OrganizationFieldIndex.PaidSubscriptionsCount, true); }
			set { SetValue((int)OrganizationFieldIndex.PaidSubscriptionsCount, value); }
		}

		/// <summary>The Phone property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."phone".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Phone
		{
			get { return (System.String)GetValue((int)OrganizationFieldIndex.Phone, true); }
			set { SetValue((int)OrganizationFieldIndex.Phone, value); }
		}

		/// <summary>The Status property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."status".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Status
		{
			get { return (System.Int16)GetValue((int)OrganizationFieldIndex.Status, true); }
			set { SetValue((int)OrganizationFieldIndex.Status, value); }
		}

		/// <summary>The TaxCode property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."tax_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String TaxCode
		{
			get { return (System.String)GetValue((int)OrganizationFieldIndex.TaxCode, true); }
			set { SetValue((int)OrganizationFieldIndex.TaxCode, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Organization<br/><br/></summary>
		/// <remarks>Mapped on  table field: "organizations"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OrganizationFieldIndex.UpdatedAt, false); }
			set { SetValue((int)OrganizationFieldIndex.UpdatedAt, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'OrganizationBankingEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrganizationBankingEntity))]
		public virtual EntityCollection<OrganizationBankingEntity> OrganizationBankings { get { return GetOrCreateEntityCollection<OrganizationBankingEntity, OrganizationBankingEntityFactory>("Organization", true, false, ref _organizationBankings); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrganizationUserEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrganizationUserEntity))]
		public virtual EntityCollection<OrganizationUserEntity> OrganizationUsers { get { return GetOrCreateEntityCollection<OrganizationUserEntity, OrganizationUserEntityFactory>("Organization", true, false, ref _organizationUsers); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Organizations
{
	public enum OrganizationFieldIndex
	{
		///<summary>Address. </summary>
		Address,
		///<summary>Code. </summary>
		Code,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Email. </summary>
		Email,
		///<summary>FirstTrialAt. </summary>
		FirstTrialAt,
		///<summary>HasEverPaid. </summary>
		HasEverPaid,
		///<summary>Id. </summary>
		Id,
		///<summary>Mail. </summary>
		Mail,
		///<summary>Name. </summary>
		Name,
		///<summary>PaidSubscriptionsCount. </summary>
		PaidSubscriptionsCount,
		///<summary>Phone. </summary>
		Phone,
		///<summary>Status. </summary>
		Status,
		///<summary>TaxCode. </summary>
		TaxCode,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Organizations.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Organization. </summary>
	public partial class OrganizationRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between OrganizationEntity and OrganizationBankingEntity over the 1:n relation they have, using the relation between the fields: Organization.Id - OrganizationBanking.OrganizationId</summary>
		public virtual IEntityRelation OrganizationBankingEntityUsingOrganizationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrganizationBankings", true, new[] { OrganizationFields.Id, OrganizationBankingFields.OrganizationId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrganizationEntity and OrganizationUserEntity over the 1:n relation they have, using the relation between the fields: Organization.Id - OrganizationUser.OrganizationId</summary>
		public virtual IEntityRelation OrganizationUserEntityUsingOrganizationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrganizationUsers", true, new[] { OrganizationFields.Id, OrganizationUserFields.OrganizationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOrganizationRelations
	{
		internal static readonly IEntityRelation OrganizationBankingEntityUsingOrganizationIdStatic = new OrganizationRelations().OrganizationBankingEntityUsingOrganizationId;
		internal static readonly IEntityRelation OrganizationUserEntityUsingOrganizationIdStatic = new OrganizationRelations().OrganizationUserEntityUsingOrganizationId;

		/// <summary>CTor</summary>
		static StaticOrganizationRelations() { }
	}
}
