//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Notification.HelperClasses;
using RoomManagerment.Notification.FactoryClasses;
using RoomManagerment.Notification.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Notification.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Notification'.<br/><br/></summary>
	[Serializable]
	public partial class NotificationEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<UserNotificationEntity> _userNotifications;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static NotificationEntityStaticMetaData _staticMetaData = new NotificationEntityStaticMetaData();
		private static NotificationRelations _relationsFactory = new NotificationRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name UserNotifications</summary>
			public static readonly string UserNotifications = "UserNotifications";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class NotificationEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public NotificationEntityStaticMetaData()
			{
				SetEntityCoreInfo("NotificationEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Notification.EntityType.NotificationEntity, typeof(NotificationEntity), typeof(NotificationEntityFactory), false);
				AddNavigatorMetaData<NotificationEntity, EntityCollection<UserNotificationEntity>>("UserNotifications", a => a._userNotifications, (a, b) => a._userNotifications = b, a => a.UserNotifications, () => new NotificationRelations().UserNotificationEntityUsingNotificationId, typeof(UserNotificationEntity), (int)RoomManagerment.Notification.EntityType.UserNotificationEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static NotificationEntity()
		{
		}

		/// <summary> CTor</summary>
		public NotificationEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public NotificationEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this NotificationEntity</param>
		public NotificationEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Notification which data should be fetched into this Notification object</param>
		public NotificationEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Notification which data should be fetched into this Notification object</param>
		/// <param name="validator">The custom validator object for this NotificationEntity</param>
		public NotificationEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected NotificationEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'UserNotification' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUserNotifications() { return CreateRelationInfoForNavigator("UserNotifications"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this NotificationEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static NotificationRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'UserNotification' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUserNotifications { get { return _staticMetaData.GetPrefetchPathElement("UserNotifications", CommonEntityBase.CreateEntityCollection<UserNotificationEntity>()); } }

		/// <summary>The Content property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."content".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Content
		{
			get { return (System.String)GetValue((int)NotificationFieldIndex.Content, true); }
			set { SetValue((int)NotificationFieldIndex.Content, value); }
		}

		/// <summary>The CreatedAt property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."created_at".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)NotificationFieldIndex.CreatedAt, true); }
			set { SetValue((int)NotificationFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Id property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)NotificationFieldIndex.Id, true); }
			set { SetValue((int)NotificationFieldIndex.Id, value); }
		}

		/// <summary>The Title property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."title".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Title
		{
			get { return (System.String)GetValue((int)NotificationFieldIndex.Title, true); }
			set { SetValue((int)NotificationFieldIndex.Title, value); }
		}

		/// <summary>The Type property of the Entity Notification<br/><br/></summary>
		/// <remarks>Mapped on  table field: "notifications"."type".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Type
		{
			get { return (System.String)GetValue((int)NotificationFieldIndex.Type, true); }
			set { SetValue((int)NotificationFieldIndex.Type, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'UserNotificationEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(UserNotificationEntity))]
		public virtual EntityCollection<UserNotificationEntity> UserNotifications { get { return GetOrCreateEntityCollection<UserNotificationEntity, UserNotificationEntityFactory>("Notification", true, false, ref _userNotifications); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Notification
{
	public enum NotificationFieldIndex
	{
		///<summary>Content. </summary>
		Content,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Id. </summary>
		Id,
		///<summary>Title. </summary>
		Title,
		///<summary>Type. </summary>
		Type,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Notification.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Notification. </summary>
	public partial class NotificationRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between NotificationEntity and UserNotificationEntity over the 1:n relation they have, using the relation between the fields: Notification.Id - UserNotification.NotificationId</summary>
		public virtual IEntityRelation UserNotificationEntityUsingNotificationId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "UserNotifications", true, new[] { NotificationFields.Id, UserNotificationFields.NotificationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticNotificationRelations
	{
		internal static readonly IEntityRelation UserNotificationEntityUsingNotificationIdStatic = new NotificationRelations().UserNotificationEntityUsingNotificationId;

		/// <summary>CTor</summary>
		static StaticNotificationRelations() { }
	}
}
