//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.CRM.HelperClasses
{
	/// <summary>Field Creation Class for entity BookingDepositEntity</summary>
	public partial class BookingDepositFields
	{
		/// <summary>Creates a new BookingDepositEntity.AgentId field instance</summary>
		public static EntityField2 AgentId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.AgentId); }}
		/// <summary>Creates a new BookingDepositEntity.Amount field instance</summary>
		public static EntityField2 Amount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.Amount); }}
		/// <summary>Creates a new BookingDepositEntity.ApprovedAt field instance</summary>
		public static EntityField2 ApprovedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.ApprovedAt); }}
		/// <summary>Creates a new BookingDepositEntity.ApprovedBy field instance</summary>
		public static EntityField2 ApprovedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.ApprovedBy); }}
		/// <summary>Creates a new BookingDepositEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.CreatedAt); }}
		/// <summary>Creates a new BookingDepositEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.DeletedAt); }}
		/// <summary>Creates a new BookingDepositEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.DeletedBy); }}
		/// <summary>Creates a new BookingDepositEntity.DepositType field instance</summary>
		public static EntityField2 DepositType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.DepositType); }}
		/// <summary>Creates a new BookingDepositEntity.ExpiredAt field instance</summary>
		public static EntityField2 ExpiredAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.ExpiredAt); }}
		/// <summary>Creates a new BookingDepositEntity.HoldUntil field instance</summary>
		public static EntityField2 HoldUntil { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.HoldUntil); }}
		/// <summary>Creates a new BookingDepositEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.Id); }}
		/// <summary>Creates a new BookingDepositEntity.LeadId field instance</summary>
		public static EntityField2 LeadId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.LeadId); }}
		/// <summary>Creates a new BookingDepositEntity.Notes field instance</summary>
		public static EntityField2 Notes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.Notes); }}
		/// <summary>Creates a new BookingDepositEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.OrganizationId); }}
		/// <summary>Creates a new BookingDepositEntity.PaidAt field instance</summary>
		public static EntityField2 PaidAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.PaidAt); }}
		/// <summary>Creates a new BookingDepositEntity.PaymentDetails field instance</summary>
		public static EntityField2 PaymentDetails { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.PaymentDetails); }}
		/// <summary>Creates a new BookingDepositEntity.PaymentDueDate field instance</summary>
		public static EntityField2 PaymentDueDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.PaymentDueDate); }}
		/// <summary>Creates a new BookingDepositEntity.PaymentStatus field instance</summary>
		public static EntityField2 PaymentStatus { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.PaymentStatus); }}
		/// <summary>Creates a new BookingDepositEntity.ReferenceNumber field instance</summary>
		public static EntityField2 ReferenceNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.ReferenceNumber); }}
		/// <summary>Creates a new BookingDepositEntity.TenantUserId field instance</summary>
		public static EntityField2 TenantUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.TenantUserId); }}
		/// <summary>Creates a new BookingDepositEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.UnitId); }}
		/// <summary>Creates a new BookingDepositEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new BookingDepositEntity.ViewingId field instance</summary>
		public static EntityField2 ViewingId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BookingDepositFieldIndex.ViewingId); }}
	}

	/// <summary>Field Creation Class for entity CommissionEventEntity</summary>
	public partial class CommissionEventFields
	{
		/// <summary>Creates a new CommissionEventEntity.AgentId field instance</summary>
		public static EntityField2 AgentId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.AgentId); }}
		/// <summary>Creates a new CommissionEventEntity.AmountBase field instance</summary>
		public static EntityField2 AmountBase { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.AmountBase); }}
		/// <summary>Creates a new CommissionEventEntity.CommissionTotal field instance</summary>
		public static EntityField2 CommissionTotal { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.CommissionTotal); }}
		/// <summary>Creates a new CommissionEventEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.CreatedAt); }}
		/// <summary>Creates a new CommissionEventEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.DeletedAt); }}
		/// <summary>Creates a new CommissionEventEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.DeletedBy); }}
		/// <summary>Creates a new CommissionEventEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.Id); }}
		/// <summary>Creates a new CommissionEventEntity.LeaseId field instance</summary>
		public static EntityField2 LeaseId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.LeaseId); }}
		/// <summary>Creates a new CommissionEventEntity.OccurredAt field instance</summary>
		public static EntityField2 OccurredAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.OccurredAt); }}
		/// <summary>Creates a new CommissionEventEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.OrganizationId); }}
		/// <summary>Creates a new CommissionEventEntity.PolicyId field instance</summary>
		public static EntityField2 PolicyId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.PolicyId); }}
		/// <summary>Creates a new CommissionEventEntity.RefId field instance</summary>
		public static EntityField2 RefId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.RefId); }}
		/// <summary>Creates a new CommissionEventEntity.RefType field instance</summary>
		public static EntityField2 RefType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.RefType); }}
		/// <summary>Creates a new CommissionEventEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.Status); }}
		/// <summary>Creates a new CommissionEventEntity.TriggerEvent field instance</summary>
		public static EntityField2 TriggerEvent { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.TriggerEvent); }}
		/// <summary>Creates a new CommissionEventEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.UnitId); }}
		/// <summary>Creates a new CommissionEventEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionEventFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity CommissionPolicyEntity</summary>
	public partial class CommissionPolicyFields
	{
		/// <summary>Creates a new CommissionPolicyEntity.ApplyLimitMonths field instance</summary>
		public static EntityField2 ApplyLimitMonths { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.ApplyLimitMonths); }}
		/// <summary>Creates a new CommissionPolicyEntity.Basis field instance</summary>
		public static EntityField2 Basis { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.Basis); }}
		/// <summary>Creates a new CommissionPolicyEntity.CalcType field instance</summary>
		public static EntityField2 CalcType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.CalcType); }}
		/// <summary>Creates a new CommissionPolicyEntity.CapAmount field instance</summary>
		public static EntityField2 CapAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.CapAmount); }}
		/// <summary>Creates a new CommissionPolicyEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.Code); }}
		/// <summary>Creates a new CommissionPolicyEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.CreatedAt); }}
		/// <summary>Creates a new CommissionPolicyEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.DeletedAt); }}
		/// <summary>Creates a new CommissionPolicyEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.DeletedBy); }}
		/// <summary>Creates a new CommissionPolicyEntity.FiltersJson field instance</summary>
		public static EntityField2 FiltersJson { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.FiltersJson); }}
		/// <summary>Creates a new CommissionPolicyEntity.FlatAmount field instance</summary>
		public static EntityField2 FlatAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.FlatAmount); }}
		/// <summary>Creates a new CommissionPolicyEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.Id); }}
		/// <summary>Creates a new CommissionPolicyEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.IsActive); }}
		/// <summary>Creates a new CommissionPolicyEntity.MinAmount field instance</summary>
		public static EntityField2 MinAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.MinAmount); }}
		/// <summary>Creates a new CommissionPolicyEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.OrganizationId); }}
		/// <summary>Creates a new CommissionPolicyEntity.PercentValue field instance</summary>
		public static EntityField2 PercentValue { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.PercentValue); }}
		/// <summary>Creates a new CommissionPolicyEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.Title); }}
		/// <summary>Creates a new CommissionPolicyEntity.TriggerEvent field instance</summary>
		public static EntityField2 TriggerEvent { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.TriggerEvent); }}
		/// <summary>Creates a new CommissionPolicyEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CommissionPolicyFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity LeadEntity</summary>
	public partial class LeadFields
	{
		/// <summary>Creates a new LeadEntity.AssignedTo field instance</summary>
		public static EntityField2 AssignedTo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.AssignedTo); }}
		/// <summary>Creates a new LeadEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.CreatedAt); }}
		/// <summary>Creates a new LeadEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.DeletedAt); }}
		/// <summary>Creates a new LeadEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.DeletedBy); }}
		/// <summary>Creates a new LeadEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.Email); }}
		/// <summary>Creates a new LeadEntity.FullName field instance</summary>
		public static EntityField2 FullName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.FullName); }}
		/// <summary>Creates a new LeadEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.Id); }}
		/// <summary>Creates a new LeadEntity.Notes field instance</summary>
		public static EntityField2 Notes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.Notes); }}
		/// <summary>Creates a new LeadEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.OrganizationId); }}
		/// <summary>Creates a new LeadEntity.Phone field instance</summary>
		public static EntityField2 Phone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.Phone); }}
		/// <summary>Creates a new LeadEntity.Source field instance</summary>
		public static EntityField2 Source { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.Source); }}
		/// <summary>Creates a new LeadEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.Status); }}
		/// <summary>Creates a new LeadEntity.TenantId field instance</summary>
		public static EntityField2 TenantId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.TenantId); }}
		/// <summary>Creates a new LeadEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeadFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity ReviewEntity</summary>
	public partial class ReviewFields
	{
		/// <summary>Creates a new ReviewEntity.Content field instance</summary>
		public static EntityField2 Content { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.Content); }}
		/// <summary>Creates a new ReviewEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.CreatedAt); }}
		/// <summary>Creates a new ReviewEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.DeletedAt); }}
		/// <summary>Creates a new ReviewEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.DeletedBy); }}
		/// <summary>Creates a new ReviewEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.Id); }}
		/// <summary>Creates a new ReviewEntity.IsPublic field instance</summary>
		public static EntityField2 IsPublic { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.IsPublic); }}
		/// <summary>Creates a new ReviewEntity.LeaseId field instance</summary>
		public static EntityField2 LeaseId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.LeaseId); }}
		/// <summary>Creates a new ReviewEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.OrganizationId); }}
		/// <summary>Creates a new ReviewEntity.Rating field instance</summary>
		public static EntityField2 Rating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.Rating); }}
		/// <summary>Creates a new ReviewEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.UnitId); }}
		/// <summary>Creates a new ReviewEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new ReviewEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity ReviewReplyEntity</summary>
	public partial class ReviewReplyFields
	{
		/// <summary>Creates a new ReviewReplyEntity.Content field instance</summary>
		public static EntityField2 Content { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewReplyFieldIndex.Content); }}
		/// <summary>Creates a new ReviewReplyEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewReplyFieldIndex.CreatedAt); }}
		/// <summary>Creates a new ReviewReplyEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewReplyFieldIndex.DeletedAt); }}
		/// <summary>Creates a new ReviewReplyEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewReplyFieldIndex.DeletedBy); }}
		/// <summary>Creates a new ReviewReplyEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewReplyFieldIndex.Id); }}
		/// <summary>Creates a new ReviewReplyEntity.ReviewId field instance</summary>
		public static EntityField2 ReviewId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewReplyFieldIndex.ReviewId); }}
		/// <summary>Creates a new ReviewReplyEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewReplyFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new ReviewReplyEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ReviewReplyFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity ViewingEntity</summary>
	public partial class ViewingFields
	{
		/// <summary>Creates a new ViewingEntity.AgentId field instance</summary>
		public static EntityField2 AgentId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.AgentId); }}
		/// <summary>Creates a new ViewingEntity.Checklist field instance</summary>
		public static EntityField2 Checklist { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.Checklist); }}
		/// <summary>Creates a new ViewingEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.CreatedAt); }}
		/// <summary>Creates a new ViewingEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.DeletedAt); }}
		/// <summary>Creates a new ViewingEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.DeletedBy); }}
		/// <summary>Creates a new ViewingEntity.FeedbackNotes field instance</summary>
		public static EntityField2 FeedbackNotes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.FeedbackNotes); }}
		/// <summary>Creates a new ViewingEntity.FeedbackRating field instance</summary>
		public static EntityField2 FeedbackRating { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.FeedbackRating); }}
		/// <summary>Creates a new ViewingEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.Id); }}
		/// <summary>Creates a new ViewingEntity.IsVirtual field instance</summary>
		public static EntityField2 IsVirtual { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.IsVirtual); }}
		/// <summary>Creates a new ViewingEntity.LeadEmail field instance</summary>
		public static EntityField2 LeadEmail { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.LeadEmail); }}
		/// <summary>Creates a new ViewingEntity.LeadId field instance</summary>
		public static EntityField2 LeadId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.LeadId); }}
		/// <summary>Creates a new ViewingEntity.LeadName field instance</summary>
		public static EntityField2 LeadName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.LeadName); }}
		/// <summary>Creates a new ViewingEntity.LeadPhone field instance</summary>
		public static EntityField2 LeadPhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.LeadPhone); }}
		/// <summary>Creates a new ViewingEntity.Note field instance</summary>
		public static EntityField2 Note { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.Note); }}
		/// <summary>Creates a new ViewingEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.OrganizationId); }}
		/// <summary>Creates a new ViewingEntity.PropertyId field instance</summary>
		public static EntityField2 PropertyId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.PropertyId); }}
		/// <summary>Creates a new ViewingEntity.ResultNote field instance</summary>
		public static EntityField2 ResultNote { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.ResultNote); }}
		/// <summary>Creates a new ViewingEntity.RouteData field instance</summary>
		public static EntityField2 RouteData { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.RouteData); }}
		/// <summary>Creates a new ViewingEntity.RouteOptimized field instance</summary>
		public static EntityField2 RouteOptimized { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.RouteOptimized); }}
		/// <summary>Creates a new ViewingEntity.ScheduleAt field instance</summary>
		public static EntityField2 ScheduleAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.ScheduleAt); }}
		/// <summary>Creates a new ViewingEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.Status); }}
		/// <summary>Creates a new ViewingEntity.TenantId field instance</summary>
		public static EntityField2 TenantId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.TenantId); }}
		/// <summary>Creates a new ViewingEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.UnitId); }}
		/// <summary>Creates a new ViewingEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new ViewingEntity.VirtualViewingLink field instance</summary>
		public static EntityField2 VirtualViewingLink { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ViewingFieldIndex.VirtualViewingLink); }}
	}
	

}