//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.CRM.HelperClasses;
using RoomManagerment.CRM.FactoryClasses;
using RoomManagerment.CRM.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.CRM.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'ReviewReply'.<br/><br/></summary>
	[Serializable]
	public partial class ReviewReplyEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private ReviewEntity _review;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ReviewReplyEntityStaticMetaData _staticMetaData = new ReviewReplyEntityStaticMetaData();
		private static ReviewReplyRelations _relationsFactory = new ReviewReplyRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Review</summary>
			public static readonly string Review = "Review";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ReviewReplyEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ReviewReplyEntityStaticMetaData()
			{
				SetEntityCoreInfo("ReviewReplyEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.CRM.EntityType.ReviewReplyEntity, typeof(ReviewReplyEntity), typeof(ReviewReplyEntityFactory), false);
				AddNavigatorMetaData<ReviewReplyEntity, ReviewEntity>("Review", "ReviewReplies", (a, b) => a._review = b, a => a._review, (a, b) => a.Review = b, RoomManagerment.CRM.RelationClasses.StaticReviewReplyRelations.ReviewEntityUsingReviewIdStatic, ()=>new ReviewReplyRelations().ReviewEntityUsingReviewId, null, new int[] { (int)ReviewReplyFieldIndex.ReviewId }, null, true, (int)RoomManagerment.CRM.EntityType.ReviewEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ReviewReplyEntity()
		{
		}

		/// <summary> CTor</summary>
		public ReviewReplyEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ReviewReplyEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ReviewReplyEntity</param>
		public ReviewReplyEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ReviewReply which data should be fetched into this ReviewReply object</param>
		public ReviewReplyEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ReviewReply which data should be fetched into this ReviewReply object</param>
		/// <param name="validator">The custom validator object for this ReviewReplyEntity</param>
		public ReviewReplyEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ReviewReplyEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Review' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoReview() { return CreateRelationInfoForNavigator("Review"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ReviewReplyEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ReviewReplyRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Review' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathReview { get { return _staticMetaData.GetPrefetchPathElement("Review", CommonEntityBase.CreateEntityCollection<ReviewEntity>()); } }

		/// <summary>The Content property of the Entity ReviewReply<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_replies"."content".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Content
		{
			get { return (System.String)GetValue((int)ReviewReplyFieldIndex.Content, true); }
			set { SetValue((int)ReviewReplyFieldIndex.Content, value); }
		}

		/// <summary>The CreatedAt property of the Entity ReviewReply<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_replies"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ReviewReplyFieldIndex.CreatedAt, true); }
			set { SetValue((int)ReviewReplyFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DeletedAt property of the Entity ReviewReply<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_replies"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ReviewReplyFieldIndex.DeletedAt, false); }
			set { SetValue((int)ReviewReplyFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity ReviewReply<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_replies"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)ReviewReplyFieldIndex.DeletedBy, false); }
			set { SetValue((int)ReviewReplyFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Id property of the Entity ReviewReply<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_replies"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)ReviewReplyFieldIndex.Id, true); }
			set { SetValue((int)ReviewReplyFieldIndex.Id, value); }
		}

		/// <summary>The ReviewId property of the Entity ReviewReply<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_replies"."review_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ReviewId
		{
			get { return (System.Guid)GetValue((int)ReviewReplyFieldIndex.ReviewId, true); }
			set { SetValue((int)ReviewReplyFieldIndex.ReviewId, value); }
		}

		/// <summary>The UpdatedAt property of the Entity ReviewReply<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_replies"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ReviewReplyFieldIndex.UpdatedAt, false); }
			set { SetValue((int)ReviewReplyFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserId property of the Entity ReviewReply<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_replies"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)ReviewReplyFieldIndex.UserId, true); }
			set { SetValue((int)ReviewReplyFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ReviewEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ReviewEntity Review
		{
			get { return _review; }
			set { SetSingleRelatedEntityNavigator(value, "Review"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.CRM
{
	public enum ReviewReplyFieldIndex
	{
		///<summary>Content. </summary>
		Content,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Id. </summary>
		Id,
		///<summary>ReviewId. </summary>
		ReviewId,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.CRM.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ReviewReply. </summary>
	public partial class ReviewReplyRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ReviewReplyEntity and ReviewEntity over the m:1 relation they have, using the relation between the fields: ReviewReply.ReviewId - Review.Id</summary>
		public virtual IEntityRelation ReviewEntityUsingReviewId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Review", false, new[] { ReviewFields.Id, ReviewReplyFields.ReviewId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticReviewReplyRelations
	{
		internal static readonly IEntityRelation ReviewEntityUsingReviewIdStatic = new ReviewReplyRelations().ReviewEntityUsingReviewId;

		/// <summary>CTor</summary>
		static StaticReviewReplyRelations() { }
	}
}
