//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.CRM.HelperClasses;
using RoomManagerment.CRM.FactoryClasses;
using RoomManagerment.CRM.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.CRM.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Review'.<br/><br/></summary>
	[Serializable]
	public partial class ReviewEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<ReviewReplyEntity> _reviewReplies;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ReviewEntityStaticMetaData _staticMetaData = new ReviewEntityStaticMetaData();
		private static ReviewRelations _relationsFactory = new ReviewRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name ReviewReplies</summary>
			public static readonly string ReviewReplies = "ReviewReplies";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ReviewEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ReviewEntityStaticMetaData()
			{
				SetEntityCoreInfo("ReviewEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.CRM.EntityType.ReviewEntity, typeof(ReviewEntity), typeof(ReviewEntityFactory), false);
				AddNavigatorMetaData<ReviewEntity, EntityCollection<ReviewReplyEntity>>("ReviewReplies", a => a._reviewReplies, (a, b) => a._reviewReplies = b, a => a.ReviewReplies, () => new ReviewRelations().ReviewReplyEntityUsingReviewId, typeof(ReviewReplyEntity), (int)RoomManagerment.CRM.EntityType.ReviewReplyEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ReviewEntity()
		{
		}

		/// <summary> CTor</summary>
		public ReviewEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ReviewEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ReviewEntity</param>
		public ReviewEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Review which data should be fetched into this Review object</param>
		public ReviewEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Review which data should be fetched into this Review object</param>
		/// <param name="validator">The custom validator object for this ReviewEntity</param>
		public ReviewEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ReviewEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ReviewReply' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoReviewReplies() { return CreateRelationInfoForNavigator("ReviewReplies"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ReviewEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ReviewRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ReviewReply' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathReviewReplies { get { return _staticMetaData.GetPrefetchPathElement("ReviewReplies", CommonEntityBase.CreateEntityCollection<ReviewReplyEntity>()); } }

		/// <summary>The Content property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."content".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Content
		{
			get { return (System.String)GetValue((int)ReviewFieldIndex.Content, true); }
			set { SetValue((int)ReviewFieldIndex.Content, value); }
		}

		/// <summary>The CreatedAt property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ReviewFieldIndex.CreatedAt, true); }
			set { SetValue((int)ReviewFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DeletedAt property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ReviewFieldIndex.DeletedAt, false); }
			set { SetValue((int)ReviewFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)ReviewFieldIndex.DeletedBy, false); }
			set { SetValue((int)ReviewFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Id property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)ReviewFieldIndex.Id, true); }
			set { SetValue((int)ReviewFieldIndex.Id, value); }
		}

		/// <summary>The IsPublic property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."is_public".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsPublic
		{
			get { return (System.Boolean)GetValue((int)ReviewFieldIndex.IsPublic, true); }
			set { SetValue((int)ReviewFieldIndex.IsPublic, value); }
		}

		/// <summary>The LeaseId property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."lease_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> LeaseId
		{
			get { return (Nullable<System.Guid>)GetValue((int)ReviewFieldIndex.LeaseId, false); }
			set { SetValue((int)ReviewFieldIndex.LeaseId, value); }
		}

		/// <summary>The OrganizationId property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."organization_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid OrganizationId
		{
			get { return (System.Guid)GetValue((int)ReviewFieldIndex.OrganizationId, true); }
			set { SetValue((int)ReviewFieldIndex.OrganizationId, value); }
		}

		/// <summary>The Rating property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."rating".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Rating
		{
			get { return (System.Int16)GetValue((int)ReviewFieldIndex.Rating, true); }
			set { SetValue((int)ReviewFieldIndex.Rating, value); }
		}

		/// <summary>The UnitId property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."unit_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UnitId
		{
			get { return (System.Guid)GetValue((int)ReviewFieldIndex.UnitId, true); }
			set { SetValue((int)ReviewFieldIndex.UnitId, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ReviewFieldIndex.UpdatedAt, false); }
			set { SetValue((int)ReviewFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserId property of the Entity Review<br/><br/></summary>
		/// <remarks>Mapped on  table field: "reviews"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)ReviewFieldIndex.UserId, true); }
			set { SetValue((int)ReviewFieldIndex.UserId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ReviewReplyEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ReviewReplyEntity))]
		public virtual EntityCollection<ReviewReplyEntity> ReviewReplies { get { return GetOrCreateEntityCollection<ReviewReplyEntity, ReviewReplyEntityFactory>("Review", true, false, ref _reviewReplies); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.CRM
{
	public enum ReviewFieldIndex
	{
		///<summary>Content. </summary>
		Content,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Id. </summary>
		Id,
		///<summary>IsPublic. </summary>
		IsPublic,
		///<summary>LeaseId. </summary>
		LeaseId,
		///<summary>OrganizationId. </summary>
		OrganizationId,
		///<summary>Rating. </summary>
		Rating,
		///<summary>UnitId. </summary>
		UnitId,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.CRM.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Review. </summary>
	public partial class ReviewRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ReviewEntity and ReviewReplyEntity over the 1:n relation they have, using the relation between the fields: Review.Id - ReviewReply.ReviewId</summary>
		public virtual IEntityRelation ReviewReplyEntityUsingReviewId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ReviewReplies", true, new[] { ReviewFields.Id, ReviewReplyFields.ReviewId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticReviewRelations
	{
		internal static readonly IEntityRelation ReviewReplyEntityUsingReviewIdStatic = new ReviewRelations().ReviewReplyEntityUsingReviewId;

		/// <summary>CTor</summary>
		static StaticReviewRelations() { }
	}
}
