//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Lease.HelperClasses;
using RoomManagerment.Lease.FactoryClasses;
using RoomManagerment.Lease.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Lease.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'LeaseResident'.<br/><br/></summary>
	[Serializable]
	public partial class LeaseResidentEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private LeaseEntity _lease;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static LeaseResidentEntityStaticMetaData _staticMetaData = new LeaseResidentEntityStaticMetaData();
		private static LeaseResidentRelations _relationsFactory = new LeaseResidentRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Lease</summary>
			public static readonly string Lease = "Lease";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class LeaseResidentEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public LeaseResidentEntityStaticMetaData()
			{
				SetEntityCoreInfo("LeaseResidentEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Lease.EntityType.LeaseResidentEntity, typeof(LeaseResidentEntity), typeof(LeaseResidentEntityFactory), false);
				AddNavigatorMetaData<LeaseResidentEntity, LeaseEntity>("Lease", "LeaseResidents", (a, b) => a._lease = b, a => a._lease, (a, b) => a.Lease = b, RoomManagerment.Lease.RelationClasses.StaticLeaseResidentRelations.LeaseEntityUsingLeaseIdStatic, ()=>new LeaseResidentRelations().LeaseEntityUsingLeaseId, null, new int[] { (int)LeaseResidentFieldIndex.LeaseId }, null, true, (int)RoomManagerment.Lease.EntityType.LeaseEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static LeaseResidentEntity()
		{
		}

		/// <summary> CTor</summary>
		public LeaseResidentEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public LeaseResidentEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this LeaseResidentEntity</param>
		public LeaseResidentEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for LeaseResident which data should be fetched into this LeaseResident object</param>
		public LeaseResidentEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for LeaseResident which data should be fetched into this LeaseResident object</param>
		/// <param name="validator">The custom validator object for this LeaseResidentEntity</param>
		public LeaseResidentEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected LeaseResidentEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Lease' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoLease() { return CreateRelationInfoForNavigator("Lease"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this LeaseResidentEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static LeaseResidentRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Lease' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathLease { get { return _staticMetaData.GetPrefetchPathElement("Lease", CommonEntityBase.CreateEntityCollection<LeaseEntity>()); } }

		/// <summary>The CreatedAt property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)LeaseResidentFieldIndex.CreatedAt, true); }
			set { SetValue((int)LeaseResidentFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DeletedAt property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)LeaseResidentFieldIndex.DeletedAt, false); }
			set { SetValue((int)LeaseResidentFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)LeaseResidentFieldIndex.DeletedBy, false); }
			set { SetValue((int)LeaseResidentFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Email property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."email".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Email
		{
			get { return (System.String)GetValue((int)LeaseResidentFieldIndex.Email, true); }
			set { SetValue((int)LeaseResidentFieldIndex.Email, value); }
		}

		/// <summary>The FullName property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."full_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String FullName
		{
			get { return (System.String)GetValue((int)LeaseResidentFieldIndex.FullName, true); }
			set { SetValue((int)LeaseResidentFieldIndex.FullName, value); }
		}

		/// <summary>The Id property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)LeaseResidentFieldIndex.Id, true); }
			set { SetValue((int)LeaseResidentFieldIndex.Id, value); }
		}

		/// <summary>The IdNumber property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."id_number".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String IdNumber
		{
			get { return (System.String)GetValue((int)LeaseResidentFieldIndex.IdNumber, true); }
			set { SetValue((int)LeaseResidentFieldIndex.IdNumber, value); }
		}

		/// <summary>The IsPrimary property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."is_primary".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsPrimary
		{
			get { return (System.Boolean)GetValue((int)LeaseResidentFieldIndex.IsPrimary, true); }
			set { SetValue((int)LeaseResidentFieldIndex.IsPrimary, value); }
		}

		/// <summary>The LeaseId property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."lease_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid LeaseId
		{
			get { return (System.Guid)GetValue((int)LeaseResidentFieldIndex.LeaseId, true); }
			set { SetValue((int)LeaseResidentFieldIndex.LeaseId, value); }
		}

		/// <summary>The Phone property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."phone".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Phone
		{
			get { return (System.String)GetValue((int)LeaseResidentFieldIndex.Phone, true); }
			set { SetValue((int)LeaseResidentFieldIndex.Phone, value); }
		}

		/// <summary>The Relationship property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."relationship".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Relationship
		{
			get { return (System.String)GetValue((int)LeaseResidentFieldIndex.Relationship, true); }
			set { SetValue((int)LeaseResidentFieldIndex.Relationship, value); }
		}

		/// <summary>The UpdatedAt property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)LeaseResidentFieldIndex.UpdatedAt, false); }
			set { SetValue((int)LeaseResidentFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserId property of the Entity LeaseResident<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_residents"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UserId
		{
			get { return (Nullable<System.Guid>)GetValue((int)LeaseResidentFieldIndex.UserId, false); }
			set { SetValue((int)LeaseResidentFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'LeaseEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual LeaseEntity Lease
		{
			get { return _lease; }
			set { SetSingleRelatedEntityNavigator(value, "Lease"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Lease
{
	public enum LeaseResidentFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Email. </summary>
		Email,
		///<summary>FullName. </summary>
		FullName,
		///<summary>Id. </summary>
		Id,
		///<summary>IdNumber. </summary>
		IdNumber,
		///<summary>IsPrimary. </summary>
		IsPrimary,
		///<summary>LeaseId. </summary>
		LeaseId,
		///<summary>Phone. </summary>
		Phone,
		///<summary>Relationship. </summary>
		Relationship,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Lease.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: LeaseResident. </summary>
	public partial class LeaseResidentRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between LeaseResidentEntity and LeaseEntity over the m:1 relation they have, using the relation between the fields: LeaseResident.LeaseId - Lease.Id</summary>
		public virtual IEntityRelation LeaseEntityUsingLeaseId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Lease", false, new[] { LeaseFields.Id, LeaseResidentFields.LeaseId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticLeaseResidentRelations
	{
		internal static readonly IEntityRelation LeaseEntityUsingLeaseIdStatic = new LeaseResidentRelations().LeaseEntityUsingLeaseId;

		/// <summary>CTor</summary>
		static StaticLeaseResidentRelations() { }
	}
}
