//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Lease.HelperClasses;
using RoomManagerment.Lease.FactoryClasses;
using RoomManagerment.Lease.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Lease.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'LeaseServiceSet'.<br/><br/></summary>
	[Serializable]
	public partial class LeaseServiceSetEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<LeaseServiceSetItemEntity> _leaseServiceSetItems;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static LeaseServiceSetEntityStaticMetaData _staticMetaData = new LeaseServiceSetEntityStaticMetaData();
		private static LeaseServiceSetRelations _relationsFactory = new LeaseServiceSetRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name LeaseServiceSetItems</summary>
			public static readonly string LeaseServiceSetItems = "LeaseServiceSetItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class LeaseServiceSetEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public LeaseServiceSetEntityStaticMetaData()
			{
				SetEntityCoreInfo("LeaseServiceSetEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Lease.EntityType.LeaseServiceSetEntity, typeof(LeaseServiceSetEntity), typeof(LeaseServiceSetEntityFactory), false);
				AddNavigatorMetaData<LeaseServiceSetEntity, EntityCollection<LeaseServiceSetItemEntity>>("LeaseServiceSetItems", a => a._leaseServiceSetItems, (a, b) => a._leaseServiceSetItems = b, a => a.LeaseServiceSetItems, () => new LeaseServiceSetRelations().LeaseServiceSetItemEntityUsingLeaseServiceSetId, typeof(LeaseServiceSetItemEntity), (int)RoomManagerment.Lease.EntityType.LeaseServiceSetItemEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static LeaseServiceSetEntity()
		{
		}

		/// <summary> CTor</summary>
		public LeaseServiceSetEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public LeaseServiceSetEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this LeaseServiceSetEntity</param>
		public LeaseServiceSetEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for LeaseServiceSet which data should be fetched into this LeaseServiceSet object</param>
		public LeaseServiceSetEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for LeaseServiceSet which data should be fetched into this LeaseServiceSet object</param>
		/// <param name="validator">The custom validator object for this LeaseServiceSetEntity</param>
		public LeaseServiceSetEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected LeaseServiceSetEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'LeaseServiceSetItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoLeaseServiceSetItems() { return CreateRelationInfoForNavigator("LeaseServiceSetItems"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this LeaseServiceSetEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static LeaseServiceSetRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'LeaseServiceSetItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathLeaseServiceSetItems { get { return _staticMetaData.GetPrefetchPathElement("LeaseServiceSetItems", CommonEntityBase.CreateEntityCollection<LeaseServiceSetItemEntity>()); } }

		/// <summary>The CreatedAt property of the Entity LeaseServiceSet<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_service_sets"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)LeaseServiceSetFieldIndex.CreatedAt, true); }
			set { SetValue((int)LeaseServiceSetFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DeletedAt property of the Entity LeaseServiceSet<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_service_sets"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)LeaseServiceSetFieldIndex.DeletedAt, false); }
			set { SetValue((int)LeaseServiceSetFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity LeaseServiceSet<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_service_sets"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)LeaseServiceSetFieldIndex.DeletedBy, false); }
			set { SetValue((int)LeaseServiceSetFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Description property of the Entity LeaseServiceSet<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_service_sets"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)LeaseServiceSetFieldIndex.Description, true); }
			set { SetValue((int)LeaseServiceSetFieldIndex.Description, value); }
		}

		/// <summary>The Id property of the Entity LeaseServiceSet<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_service_sets"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)LeaseServiceSetFieldIndex.Id, true); }
			set { SetValue((int)LeaseServiceSetFieldIndex.Id, value); }
		}

		/// <summary>The Name property of the Entity LeaseServiceSet<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_service_sets"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)LeaseServiceSetFieldIndex.Name, true); }
			set { SetValue((int)LeaseServiceSetFieldIndex.Name, value); }
		}

		/// <summary>The OrganizationId property of the Entity LeaseServiceSet<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_service_sets"."organization_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid OrganizationId
		{
			get { return (System.Guid)GetValue((int)LeaseServiceSetFieldIndex.OrganizationId, true); }
			set { SetValue((int)LeaseServiceSetFieldIndex.OrganizationId, value); }
		}

		/// <summary>The UpdatedAt property of the Entity LeaseServiceSet<br/><br/></summary>
		/// <remarks>Mapped on  table field: "lease_service_sets"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)LeaseServiceSetFieldIndex.UpdatedAt, false); }
			set { SetValue((int)LeaseServiceSetFieldIndex.UpdatedAt, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'LeaseServiceSetItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(LeaseServiceSetItemEntity))]
		public virtual EntityCollection<LeaseServiceSetItemEntity> LeaseServiceSetItems { get { return GetOrCreateEntityCollection<LeaseServiceSetItemEntity, LeaseServiceSetItemEntityFactory>("LeaseServiceSet", true, false, ref _leaseServiceSetItems); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Lease
{
	public enum LeaseServiceSetFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Description. </summary>
		Description,
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		///<summary>OrganizationId. </summary>
		OrganizationId,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Lease.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: LeaseServiceSet. </summary>
	public partial class LeaseServiceSetRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between LeaseServiceSetEntity and LeaseServiceSetItemEntity over the 1:n relation they have, using the relation between the fields: LeaseServiceSet.Id - LeaseServiceSetItem.LeaseServiceSetId</summary>
		public virtual IEntityRelation LeaseServiceSetItemEntityUsingLeaseServiceSetId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "LeaseServiceSetItems", true, new[] { LeaseServiceSetFields.Id, LeaseServiceSetItemFields.LeaseServiceSetId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticLeaseServiceSetRelations
	{
		internal static readonly IEntityRelation LeaseServiceSetItemEntityUsingLeaseServiceSetIdStatic = new LeaseServiceSetRelations().LeaseServiceSetItemEntityUsingLeaseServiceSetId;

		/// <summary>CTor</summary>
		static StaticLeaseServiceSetRelations() { }
	}
}
