//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Lease.HelperClasses
{
	/// <summary>Field Creation Class for entity LeaseEntity</summary>
	public partial class LeaseFields
	{
		/// <summary>Creates a new LeaseEntity.BookingId field instance</summary>
		public static EntityField2 BookingId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.BookingId); }}
		/// <summary>Creates a new LeaseEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.CreatedAt); }}
		/// <summary>Creates a new LeaseEntity.CycleId field instance</summary>
		public static EntityField2 CycleId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.CycleId); }}
		/// <summary>Creates a new LeaseEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.DeletedAt); }}
		/// <summary>Creates a new LeaseEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.DeletedBy); }}
		/// <summary>Creates a new LeaseEntity.DepositAmount field instance</summary>
		public static EntityField2 DepositAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.DepositAmount); }}
		/// <summary>Creates a new LeaseEntity.EndDate field instance</summary>
		public static EntityField2 EndDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.EndDate); }}
		/// <summary>Creates a new LeaseEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.Id); }}
		/// <summary>Creates a new LeaseEntity.LeaseNo field instance</summary>
		public static EntityField2 LeaseNo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.LeaseNo); }}
		/// <summary>Creates a new LeaseEntity.Notes field instance</summary>
		public static EntityField2 Notes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.Notes); }}
		/// <summary>Creates a new LeaseEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.OrganizationId); }}
		/// <summary>Creates a new LeaseEntity.ParentLeaseId field instance</summary>
		public static EntityField2 ParentLeaseId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.ParentLeaseId); }}
		/// <summary>Creates a new LeaseEntity.PaymentDay field instance</summary>
		public static EntityField2 PaymentDay { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.PaymentDay); }}
		/// <summary>Creates a new LeaseEntity.RentAmount field instance</summary>
		public static EntityField2 RentAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.RentAmount); }}
		/// <summary>Creates a new LeaseEntity.StartDate field instance</summary>
		public static EntityField2 StartDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.StartDate); }}
		/// <summary>Creates a new LeaseEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.Status); }}
		/// <summary>Creates a new LeaseEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.UnitId); }}
		/// <summary>Creates a new LeaseEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity LeaseResidentEntity</summary>
	public partial class LeaseResidentFields
	{
		/// <summary>Creates a new LeaseResidentEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.CreatedAt); }}
		/// <summary>Creates a new LeaseResidentEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.DeletedAt); }}
		/// <summary>Creates a new LeaseResidentEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.DeletedBy); }}
		/// <summary>Creates a new LeaseResidentEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.Email); }}
		/// <summary>Creates a new LeaseResidentEntity.FullName field instance</summary>
		public static EntityField2 FullName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.FullName); }}
		/// <summary>Creates a new LeaseResidentEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.Id); }}
		/// <summary>Creates a new LeaseResidentEntity.IdNumber field instance</summary>
		public static EntityField2 IdNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.IdNumber); }}
		/// <summary>Creates a new LeaseResidentEntity.IsPrimary field instance</summary>
		public static EntityField2 IsPrimary { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.IsPrimary); }}
		/// <summary>Creates a new LeaseResidentEntity.LeaseId field instance</summary>
		public static EntityField2 LeaseId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.LeaseId); }}
		/// <summary>Creates a new LeaseResidentEntity.Phone field instance</summary>
		public static EntityField2 Phone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.Phone); }}
		/// <summary>Creates a new LeaseResidentEntity.Relationship field instance</summary>
		public static EntityField2 Relationship { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.Relationship); }}
		/// <summary>Creates a new LeaseResidentEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new LeaseResidentEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseResidentFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity LeaseServiceSetEntity</summary>
	public partial class LeaseServiceSetFields
	{
		/// <summary>Creates a new LeaseServiceSetEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetFieldIndex.CreatedAt); }}
		/// <summary>Creates a new LeaseServiceSetEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetFieldIndex.DeletedAt); }}
		/// <summary>Creates a new LeaseServiceSetEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetFieldIndex.DeletedBy); }}
		/// <summary>Creates a new LeaseServiceSetEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetFieldIndex.Description); }}
		/// <summary>Creates a new LeaseServiceSetEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetFieldIndex.Id); }}
		/// <summary>Creates a new LeaseServiceSetEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetFieldIndex.Name); }}
		/// <summary>Creates a new LeaseServiceSetEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetFieldIndex.OrganizationId); }}
		/// <summary>Creates a new LeaseServiceSetEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity LeaseServiceSetItemEntity</summary>
	public partial class LeaseServiceSetItemFields
	{
		/// <summary>Creates a new LeaseServiceSetItemEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.CreatedAt); }}
		/// <summary>Creates a new LeaseServiceSetItemEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.DeletedAt); }}
		/// <summary>Creates a new LeaseServiceSetItemEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.DeletedBy); }}
		/// <summary>Creates a new LeaseServiceSetItemEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.Id); }}
		/// <summary>Creates a new LeaseServiceSetItemEntity.IsRequired field instance</summary>
		public static EntityField2 IsRequired { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.IsRequired); }}
		/// <summary>Creates a new LeaseServiceSetItemEntity.LeaseServiceSetId field instance</summary>
		public static EntityField2 LeaseServiceSetId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.LeaseServiceSetId); }}
		/// <summary>Creates a new LeaseServiceSetItemEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.Price); }}
		/// <summary>Creates a new LeaseServiceSetItemEntity.ServiceId field instance</summary>
		public static EntityField2 ServiceId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.ServiceId); }}
		/// <summary>Creates a new LeaseServiceSetItemEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(LeaseServiceSetItemFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity MasterLeaseEntity</summary>
	public partial class MasterLeaseFields
	{
		/// <summary>Creates a new MasterLeaseEntity.ContractNo field instance</summary>
		public static EntityField2 ContractNo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.ContractNo); }}
		/// <summary>Creates a new MasterLeaseEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.CreatedAt); }}
		/// <summary>Creates a new MasterLeaseEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.DeletedAt); }}
		/// <summary>Creates a new MasterLeaseEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.DeletedBy); }}
		/// <summary>Creates a new MasterLeaseEntity.DepositAmount field instance</summary>
		public static EntityField2 DepositAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.DepositAmount); }}
		/// <summary>Creates a new MasterLeaseEntity.EndDate field instance</summary>
		public static EntityField2 EndDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.EndDate); }}
		/// <summary>Creates a new MasterLeaseEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.Id); }}
		/// <summary>Creates a new MasterLeaseEntity.LandlordUserId field instance</summary>
		public static EntityField2 LandlordUserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.LandlordUserId); }}
		/// <summary>Creates a new MasterLeaseEntity.Notes field instance</summary>
		public static EntityField2 Notes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.Notes); }}
		/// <summary>Creates a new MasterLeaseEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.OrganizationId); }}
		/// <summary>Creates a new MasterLeaseEntity.PaymentDay field instance</summary>
		public static EntityField2 PaymentDay { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.PaymentDay); }}
		/// <summary>Creates a new MasterLeaseEntity.PropertyId field instance</summary>
		public static EntityField2 PropertyId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.PropertyId); }}
		/// <summary>Creates a new MasterLeaseEntity.RentAmount field instance</summary>
		public static EntityField2 RentAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.RentAmount); }}
		/// <summary>Creates a new MasterLeaseEntity.StartDate field instance</summary>
		public static EntityField2 StartDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.StartDate); }}
		/// <summary>Creates a new MasterLeaseEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.Status); }}
		/// <summary>Creates a new MasterLeaseEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MasterLeaseFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity PaymentCycleEntity</summary>
	public partial class PaymentCycleFields
	{
		/// <summary>Creates a new PaymentCycleEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.CreatedAt); }}
		/// <summary>Creates a new PaymentCycleEntity.DayOfMonth field instance</summary>
		public static EntityField2 DayOfMonth { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.DayOfMonth); }}
		/// <summary>Creates a new PaymentCycleEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.DeletedAt); }}
		/// <summary>Creates a new PaymentCycleEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.DeletedBy); }}
		/// <summary>Creates a new PaymentCycleEntity.DurationMonths field instance</summary>
		public static EntityField2 DurationMonths { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.DurationMonths); }}
		/// <summary>Creates a new PaymentCycleEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.Id); }}
		/// <summary>Creates a new PaymentCycleEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.Name); }}
		/// <summary>Creates a new PaymentCycleEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.OrganizationId); }}
		/// <summary>Creates a new PaymentCycleEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PaymentCycleFieldIndex.UpdatedAt); }}
	}
	

}