//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Identity.HelperClasses;
using RoomManagerment.Identity.FactoryClasses;
using RoomManagerment.Identity.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Identity.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Menu'.<br/><br/></summary>
	[Serializable]
	public partial class MenuEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<MenuPermissionEntity> _menuPermissions;
		private EntityCollection<UserMenuOverrideEntity> _userMenuOverrides;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static MenuEntityStaticMetaData _staticMetaData = new MenuEntityStaticMetaData();
		private static MenuRelations _relationsFactory = new MenuRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name MenuPermissions</summary>
			public static readonly string MenuPermissions = "MenuPermissions";
			/// <summary>Member name UserMenuOverrides</summary>
			public static readonly string UserMenuOverrides = "UserMenuOverrides";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class MenuEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public MenuEntityStaticMetaData()
			{
				SetEntityCoreInfo("MenuEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Identity.EntityType.MenuEntity, typeof(MenuEntity), typeof(MenuEntityFactory), false);
				AddNavigatorMetaData<MenuEntity, EntityCollection<MenuPermissionEntity>>("MenuPermissions", a => a._menuPermissions, (a, b) => a._menuPermissions = b, a => a.MenuPermissions, () => new MenuRelations().MenuPermissionEntityUsingMenuId, typeof(MenuPermissionEntity), (int)RoomManagerment.Identity.EntityType.MenuPermissionEntity);
				AddNavigatorMetaData<MenuEntity, EntityCollection<UserMenuOverrideEntity>>("UserMenuOverrides", a => a._userMenuOverrides, (a, b) => a._userMenuOverrides = b, a => a.UserMenuOverrides, () => new MenuRelations().UserMenuOverrideEntityUsingMenuId, typeof(UserMenuOverrideEntity), (int)RoomManagerment.Identity.EntityType.UserMenuOverrideEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static MenuEntity()
		{
		}

		/// <summary> CTor</summary>
		public MenuEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public MenuEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this MenuEntity</param>
		public MenuEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Menu which data should be fetched into this Menu object</param>
		public MenuEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Menu which data should be fetched into this Menu object</param>
		/// <param name="validator">The custom validator object for this MenuEntity</param>
		public MenuEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected MenuEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'MenuPermission' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoMenuPermissions() { return CreateRelationInfoForNavigator("MenuPermissions"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'UserMenuOverride' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUserMenuOverrides() { return CreateRelationInfoForNavigator("UserMenuOverrides"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this MenuEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static MenuRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'MenuPermission' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathMenuPermissions { get { return _staticMetaData.GetPrefetchPathElement("MenuPermissions", CommonEntityBase.CreateEntityCollection<MenuPermissionEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'UserMenuOverride' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUserMenuOverrides { get { return _staticMetaData.GetPrefetchPathElement("UserMenuOverrides", CommonEntityBase.CreateEntityCollection<UserMenuOverrideEntity>()); } }

		/// <summary>The Code property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)MenuFieldIndex.Code, true); }
			set { SetValue((int)MenuFieldIndex.Code, value); }
		}

		/// <summary>The CreatedAt property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)MenuFieldIndex.CreatedAt, true); }
			set { SetValue((int)MenuFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Icon property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."icon".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Icon
		{
			get { return (System.String)GetValue((int)MenuFieldIndex.Icon, true); }
			set { SetValue((int)MenuFieldIndex.Icon, value); }
		}

		/// <summary>The Id property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)MenuFieldIndex.Id, true); }
			set { SetValue((int)MenuFieldIndex.Id, value); }
		}

		/// <summary>The IsActive property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsActive
		{
			get { return (System.Boolean)GetValue((int)MenuFieldIndex.IsActive, true); }
			set { SetValue((int)MenuFieldIndex.IsActive, value); }
		}

		/// <summary>The Label property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."label".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Label
		{
			get { return (System.String)GetValue((int)MenuFieldIndex.Label, true); }
			set { SetValue((int)MenuFieldIndex.Label, value); }
		}

		/// <summary>The OrderIndex property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."order_index".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 OrderIndex
		{
			get { return (System.Int32)GetValue((int)MenuFieldIndex.OrderIndex, true); }
			set { SetValue((int)MenuFieldIndex.OrderIndex, value); }
		}

		/// <summary>The ParentId property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."parent_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> ParentId
		{
			get { return (Nullable<System.Guid>)GetValue((int)MenuFieldIndex.ParentId, false); }
			set { SetValue((int)MenuFieldIndex.ParentId, value); }
		}

		/// <summary>The Path property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."path".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 300.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Path
		{
			get { return (System.String)GetValue((int)MenuFieldIndex.Path, true); }
			set { SetValue((int)MenuFieldIndex.Path, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Menu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "menus"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)MenuFieldIndex.UpdatedAt, false); }
			set { SetValue((int)MenuFieldIndex.UpdatedAt, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'MenuPermissionEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(MenuPermissionEntity))]
		public virtual EntityCollection<MenuPermissionEntity> MenuPermissions { get { return GetOrCreateEntityCollection<MenuPermissionEntity, MenuPermissionEntityFactory>("Menu", true, false, ref _menuPermissions); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'UserMenuOverrideEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(UserMenuOverrideEntity))]
		public virtual EntityCollection<UserMenuOverrideEntity> UserMenuOverrides { get { return GetOrCreateEntityCollection<UserMenuOverrideEntity, UserMenuOverrideEntityFactory>("Menu", true, false, ref _userMenuOverrides); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Identity
{
	public enum MenuFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Icon. </summary>
		Icon,
		///<summary>Id. </summary>
		Id,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>Label. </summary>
		Label,
		///<summary>OrderIndex. </summary>
		OrderIndex,
		///<summary>ParentId. </summary>
		ParentId,
		///<summary>Path. </summary>
		Path,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Identity.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Menu. </summary>
	public partial class MenuRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between MenuEntity and MenuPermissionEntity over the 1:n relation they have, using the relation between the fields: Menu.Id - MenuPermission.MenuId</summary>
		public virtual IEntityRelation MenuPermissionEntityUsingMenuId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "MenuPermissions", true, new[] { MenuFields.Id, MenuPermissionFields.MenuId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between MenuEntity and UserMenuOverrideEntity over the 1:n relation they have, using the relation between the fields: Menu.Id - UserMenuOverride.MenuId</summary>
		public virtual IEntityRelation UserMenuOverrideEntityUsingMenuId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "UserMenuOverrides", true, new[] { MenuFields.Id, UserMenuOverrideFields.MenuId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticMenuRelations
	{
		internal static readonly IEntityRelation MenuPermissionEntityUsingMenuIdStatic = new MenuRelations().MenuPermissionEntityUsingMenuId;
		internal static readonly IEntityRelation UserMenuOverrideEntityUsingMenuIdStatic = new MenuRelations().UserMenuOverrideEntityUsingMenuId;

		/// <summary>CTor</summary>
		static StaticMenuRelations() { }
	}
}
