//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Identity.HelperClasses;
using RoomManagerment.Identity.FactoryClasses;
using RoomManagerment.Identity.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Identity.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Permission'.<br/><br/></summary>
	[Serializable]
	public partial class PermissionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<RolePermissionEntity> _rolePermissions;
		private EntityCollection<UserPermissionEntity> _userPermissions;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static PermissionEntityStaticMetaData _staticMetaData = new PermissionEntityStaticMetaData();
		private static PermissionRelations _relationsFactory = new PermissionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name RolePermissions</summary>
			public static readonly string RolePermissions = "RolePermissions";
			/// <summary>Member name UserPermissions</summary>
			public static readonly string UserPermissions = "UserPermissions";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PermissionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PermissionEntityStaticMetaData()
			{
				SetEntityCoreInfo("PermissionEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Identity.EntityType.PermissionEntity, typeof(PermissionEntity), typeof(PermissionEntityFactory), false);
				AddNavigatorMetaData<PermissionEntity, EntityCollection<RolePermissionEntity>>("RolePermissions", a => a._rolePermissions, (a, b) => a._rolePermissions = b, a => a.RolePermissions, () => new PermissionRelations().RolePermissionEntityUsingPermissionId, typeof(RolePermissionEntity), (int)RoomManagerment.Identity.EntityType.RolePermissionEntity);
				AddNavigatorMetaData<PermissionEntity, EntityCollection<UserPermissionEntity>>("UserPermissions", a => a._userPermissions, (a, b) => a._userPermissions = b, a => a.UserPermissions, () => new PermissionRelations().UserPermissionEntityUsingPermissionId, typeof(UserPermissionEntity), (int)RoomManagerment.Identity.EntityType.UserPermissionEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PermissionEntity()
		{
		}

		/// <summary> CTor</summary>
		public PermissionEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PermissionEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PermissionEntity</param>
		public PermissionEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Permission which data should be fetched into this Permission object</param>
		public PermissionEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Permission which data should be fetched into this Permission object</param>
		/// <param name="validator">The custom validator object for this PermissionEntity</param>
		public PermissionEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PermissionEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'RolePermission' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoRolePermissions() { return CreateRelationInfoForNavigator("RolePermissions"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'UserPermission' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUserPermissions() { return CreateRelationInfoForNavigator("UserPermissions"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PermissionEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PermissionRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'RolePermission' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathRolePermissions { get { return _staticMetaData.GetPrefetchPathElement("RolePermissions", CommonEntityBase.CreateEntityCollection<RolePermissionEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'UserPermission' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUserPermissions { get { return _staticMetaData.GetPrefetchPathElement("UserPermissions", CommonEntityBase.CreateEntityCollection<UserPermissionEntity>()); } }

		/// <summary>The Code property of the Entity Permission<br/><br/></summary>
		/// <remarks>Mapped on  table field: "permissions"."code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)PermissionFieldIndex.Code, true); }
			set { SetValue((int)PermissionFieldIndex.Code, value); }
		}

		/// <summary>The CreatedAt property of the Entity Permission<br/><br/></summary>
		/// <remarks>Mapped on  table field: "permissions"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)PermissionFieldIndex.CreatedAt, true); }
			set { SetValue((int)PermissionFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Id property of the Entity Permission<br/><br/></summary>
		/// <remarks>Mapped on  table field: "permissions"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)PermissionFieldIndex.Id, true); }
			set { SetValue((int)PermissionFieldIndex.Id, value); }
		}

		/// <summary>The Name property of the Entity Permission<br/><br/></summary>
		/// <remarks>Mapped on  table field: "permissions"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)PermissionFieldIndex.Name, true); }
			set { SetValue((int)PermissionFieldIndex.Name, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'RolePermissionEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(RolePermissionEntity))]
		public virtual EntityCollection<RolePermissionEntity> RolePermissions { get { return GetOrCreateEntityCollection<RolePermissionEntity, RolePermissionEntityFactory>("Permission", true, false, ref _rolePermissions); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'UserPermissionEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(UserPermissionEntity))]
		public virtual EntityCollection<UserPermissionEntity> UserPermissions { get { return GetOrCreateEntityCollection<UserPermissionEntity, UserPermissionEntityFactory>("Permission", true, false, ref _userPermissions); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Identity
{
	public enum PermissionFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Identity.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Permission. </summary>
	public partial class PermissionRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between PermissionEntity and RolePermissionEntity over the 1:n relation they have, using the relation between the fields: Permission.Id - RolePermission.PermissionId</summary>
		public virtual IEntityRelation RolePermissionEntityUsingPermissionId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "RolePermissions", true, new[] { PermissionFields.Id, RolePermissionFields.PermissionId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PermissionEntity and UserPermissionEntity over the 1:n relation they have, using the relation between the fields: Permission.Id - UserPermission.PermissionId</summary>
		public virtual IEntityRelation UserPermissionEntityUsingPermissionId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "UserPermissions", true, new[] { PermissionFields.Id, UserPermissionFields.PermissionId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPermissionRelations
	{
		internal static readonly IEntityRelation RolePermissionEntityUsingPermissionIdStatic = new PermissionRelations().RolePermissionEntityUsingPermissionId;
		internal static readonly IEntityRelation UserPermissionEntityUsingPermissionIdStatic = new PermissionRelations().UserPermissionEntityUsingPermissionId;

		/// <summary>CTor</summary>
		static StaticPermissionRelations() { }
	}
}
