//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Identity.HelperClasses;
using RoomManagerment.Identity.FactoryClasses;
using RoomManagerment.Identity.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Identity.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'UserProfile'.<br/><br/></summary>
	[Serializable]
	public partial class UserProfileEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private UserEntity _user;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static UserProfileEntityStaticMetaData _staticMetaData = new UserProfileEntityStaticMetaData();
		private static UserProfileRelations _relationsFactory = new UserProfileRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class UserProfileEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public UserProfileEntityStaticMetaData()
			{
				SetEntityCoreInfo("UserProfileEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Identity.EntityType.UserProfileEntity, typeof(UserProfileEntity), typeof(UserProfileEntityFactory), false);
				AddNavigatorMetaData<UserProfileEntity, UserEntity>("User", "UserProfile", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, RoomManagerment.Identity.RelationClasses.StaticUserProfileRelations.UserEntityUsingUserIdStatic, ()=>new UserProfileRelations().UserEntityUsingUserId, null, new int[] { (int)UserProfileFieldIndex.UserId }, null, false, (int)RoomManagerment.Identity.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static UserProfileEntity()
		{
		}

		/// <summary> CTor</summary>
		public UserProfileEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public UserProfileEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this UserProfileEntity</param>
		public UserProfileEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="userId">PK value for UserProfile which data should be fetched into this UserProfile object</param>
		public UserProfileEntity(System.Guid userId) : this(userId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="userId">PK value for UserProfile which data should be fetched into this UserProfile object</param>
		/// <param name="validator">The custom validator object for this UserProfileEntity</param>
		public UserProfileEntity(System.Guid userId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.UserId = userId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected UserProfileEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this UserProfileEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static UserProfileRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The AvatarUrl property of the Entity UserProfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_profiles"."avatar_url".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String AvatarUrl
		{
			get { return (System.String)GetValue((int)UserProfileFieldIndex.AvatarUrl, true); }
			set { SetValue((int)UserProfileFieldIndex.AvatarUrl, value); }
		}

		/// <summary>The CreatedAt property of the Entity UserProfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_profiles"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)UserProfileFieldIndex.CreatedAt, true); }
			set { SetValue((int)UserProfileFieldIndex.CreatedAt, value); }
		}

		/// <summary>The FullName property of the Entity UserProfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_profiles"."full_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String FullName
		{
			get { return (System.String)GetValue((int)UserProfileFieldIndex.FullName, true); }
			set { SetValue((int)UserProfileFieldIndex.FullName, value); }
		}

		/// <summary>The Phone property of the Entity UserProfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_profiles"."phone".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 30.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Phone
		{
			get { return (System.String)GetValue((int)UserProfileFieldIndex.Phone, true); }
			set { SetValue((int)UserProfileFieldIndex.Phone, value); }
		}

		/// <summary>The SearchVector property of the Entity UserProfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_profiles"."search_vector".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SearchVector
		{
			get { return (System.String)GetValue((int)UserProfileFieldIndex.SearchVector, true); }
			set { SetValue((int)UserProfileFieldIndex.SearchVector, value); }
		}

		/// <summary>The UpdatedAt property of the Entity UserProfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_profiles"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)UserProfileFieldIndex.UpdatedAt, false); }
			set { SetValue((int)UserProfileFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserId property of the Entity UserProfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_profiles"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)UserProfileFieldIndex.UserId, true); }
			set { SetValue((int)UserProfileFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned.<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Identity
{
	public enum UserProfileFieldIndex
	{
		///<summary>AvatarUrl. </summary>
		AvatarUrl,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>FullName. </summary>
		FullName,
		///<summary>Phone. </summary>
		Phone,
		///<summary>SearchVector. </summary>
		SearchVector,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Identity.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: UserProfile. </summary>
	public partial class UserProfileRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between UserProfileEntity and UserEntity over the 1:1 relation they have, using the relation between the fields: UserProfile.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToOne, "User", false, new[] { UserFields.Id, UserProfileFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticUserProfileRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new UserProfileRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticUserProfileRelations() { }
	}
}
