//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using RoomManagerment.Identity.EntityClasses;
using RoomManagerment.Identity.HelperClasses;
using RoomManagerment.Identity.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Identity.FactoryClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END


	/// <summary>general base class for the generated factories</summary>
	[Serializable]
	public partial class EntityFactoryBase2<TEntity> : EntityFactoryCore2
		where TEntity : EntityBase2, IEntity2
	{
		private readonly bool _isInHierarchy;

		/// <summary>CTor</summary>
		/// <param name="entityName">Name of the entity.</param>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <param name="isInHierarchy">If true, the entity of this factory is in an inheritance hierarchy, false otherwise</param>
		public EntityFactoryBase2(string entityName, RoomManagerment.Identity.EntityType typeOfEntity, bool isInHierarchy) : base(entityName, (int)typeOfEntity)
		{
			_isInHierarchy = isInHierarchy;
		}
		
		/// <inheritdoc/>
		public override IEntityFields2 CreateFields() { return ModelInfoProviderSingleton.GetInstance().GetEntityFields(this.ForEntityName); }
		
		/// <inheritdoc/>
		public override IEntity2 CreateEntityFromEntityTypeValue(int entityTypeValue) {	return GeneralEntityFactory.Create((RoomManagerment.Identity.EntityType)entityTypeValue); }

		/// <inheritdoc/>
		public override IRelationCollection CreateHierarchyRelations(string objectAlias) { return ModelInfoProviderSingleton.GetInstance().GetHierarchyRelations(this.ForEntityName, objectAlias); }

		/// <inheritdoc/>
		public override IEntityFactory2 GetEntityFactory(object[] fieldValues, Dictionary<string, int> entityFieldStartIndexesPerEntity) 
		{
			return (IEntityFactory2)ModelInfoProviderSingleton.GetInstance().GetEntityFactory(this.ForEntityName, fieldValues, entityFieldStartIndexesPerEntity) ?? this;
		}
		
		/// <inheritdoc/>
		public override IPredicateExpression GetEntityTypeFilter(bool negate, string objectAlias) {	return ModelInfoProviderSingleton.GetInstance().GetEntityTypeFilter(this.ForEntityName, objectAlias, negate);	}
						
		/// <inheritdoc/>
		public override IEntityCollection2 CreateEntityCollection()	{ return new EntityCollection<TEntity>(this); }
		
		/// <inheritdoc/>
		public override IEntityFields2 CreateHierarchyFields() 
		{
			return _isInHierarchy ? new EntityFields2(ModelInfoProviderSingleton.GetInstance().GetHierarchyFields(this.ForEntityName), ModelInfoProviderSingleton.GetInstance(), null) : base.CreateHierarchyFields();
		}
		
		/// <inheritdoc/>
		protected override Type ForEntityType { get { return typeof(TEntity); } }
	}

	/// <summary>Factory to create new, empty PermissionEntity objects.</summary>
	[Serializable]
	public partial class PermissionEntityFactory : EntityFactoryBase2<PermissionEntity> 
	{
		/// <summary>CTor</summary>
		public PermissionEntityFactory() : base("PermissionEntity", RoomManagerment.Identity.EntityType.PermissionEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new PermissionEntity(fields); }
	}

	/// <summary>Factory to create new, empty RefreshTokenEntity objects.</summary>
	[Serializable]
	public partial class RefreshTokenEntityFactory : EntityFactoryBase2<RefreshTokenEntity> 
	{
		/// <summary>CTor</summary>
		public RefreshTokenEntityFactory() : base("RefreshTokenEntity", RoomManagerment.Identity.EntityType.RefreshTokenEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new RefreshTokenEntity(fields); }
	}

	/// <summary>Factory to create new, empty RoleEntity objects.</summary>
	[Serializable]
	public partial class RoleEntityFactory : EntityFactoryBase2<RoleEntity> 
	{
		/// <summary>CTor</summary>
		public RoleEntityFactory() : base("RoleEntity", RoomManagerment.Identity.EntityType.RoleEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new RoleEntity(fields); }
	}

	/// <summary>Factory to create new, empty RolePermissionEntity objects.</summary>
	[Serializable]
	public partial class RolePermissionEntityFactory : EntityFactoryBase2<RolePermissionEntity> 
	{
		/// <summary>CTor</summary>
		public RolePermissionEntityFactory() : base("RolePermissionEntity", RoomManagerment.Identity.EntityType.RolePermissionEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new RolePermissionEntity(fields); }
	}

	/// <summary>Factory to create new, empty UserEntity objects.</summary>
	[Serializable]
	public partial class UserEntityFactory : EntityFactoryBase2<UserEntity> 
	{
		/// <summary>CTor</summary>
		public UserEntityFactory() : base("UserEntity", RoomManagerment.Identity.EntityType.UserEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new UserEntity(fields); }
	}

	/// <summary>Factory to create new, empty UserPermissionEntity objects.</summary>
	[Serializable]
	public partial class UserPermissionEntityFactory : EntityFactoryBase2<UserPermissionEntity> 
	{
		/// <summary>CTor</summary>
		public UserPermissionEntityFactory() : base("UserPermissionEntity", RoomManagerment.Identity.EntityType.UserPermissionEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new UserPermissionEntity(fields); }
	}

	/// <summary>Factory to create new, empty UserProfileEntity objects.</summary>
	[Serializable]
	public partial class UserProfileEntityFactory : EntityFactoryBase2<UserProfileEntity> 
	{
		/// <summary>CTor</summary>
		public UserProfileEntityFactory() : base("UserProfileEntity", RoomManagerment.Identity.EntityType.UserProfileEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new UserProfileEntity(fields); }
	}

	/// <summary>Factory to create new, empty UserRoleEntity objects.</summary>
	[Serializable]
	public partial class UserRoleEntityFactory : EntityFactoryBase2<UserRoleEntity> 
	{
		/// <summary>CTor</summary>
		public UserRoleEntityFactory() : base("UserRoleEntity", RoomManagerment.Identity.EntityType.UserRoleEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new UserRoleEntity(fields); }
	}

	/// <summary>Factory to create new, empty MenuEntity objects.</summary>
	[Serializable]
	public partial class MenuEntityFactory : EntityFactoryBase2<MenuEntity> 
	{
		/// <summary>CTor</summary>
		public MenuEntityFactory() : base("MenuEntity", RoomManagerment.Identity.EntityType.MenuEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new MenuEntity(fields); }
	}

	/// <summary>Factory to create new, empty MenuPermissionEntity objects.</summary>
	[Serializable]
	public partial class MenuPermissionEntityFactory : EntityFactoryBase2<MenuPermissionEntity> 
	{
		/// <summary>CTor</summary>
		public MenuPermissionEntityFactory() : base("MenuPermissionEntity", RoomManagerment.Identity.EntityType.MenuPermissionEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new MenuPermissionEntity(fields); }
	}

	/// <summary>Factory to create new, empty UserMenuOverrideEntity objects.</summary>
	[Serializable]
	public partial class UserMenuOverrideEntityFactory : EntityFactoryBase2<UserMenuOverrideEntity> 
	{
		/// <summary>CTor</summary>
		public UserMenuOverrideEntityFactory() : base("UserMenuOverrideEntity", RoomManagerment.Identity.EntityType.UserMenuOverrideEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new UserMenuOverrideEntity(fields); }
	}

	/// <summary>Factory to create new, empty Entity objects based on the entity type specified. Uses  entity specific factory objects</summary>
	[Serializable]
	public partial class GeneralEntityFactory
	{
		/// <summary>Creates a new, empty Entity object of the type specified</summary>
		/// <param name="entityTypeToCreate">The entity type to create.</param>
		/// <returns>A new, empty Entity object.</returns>
		public static IEntity2 Create(RoomManagerment.Identity.EntityType entityTypeToCreate)
		{
			var factoryToUse = EntityFactoryFactory.GetFactory(entityTypeToCreate);
			IEntity2 toReturn = null;
			if(factoryToUse != null)
			{
				toReturn = factoryToUse.Create();
			}
			return toReturn;
		}		
	}
		
	/// <summary>Class which is used to obtain the entity factory based on the .NET type of the entity. </summary>
	[Serializable]
	public static class EntityFactoryFactory
	{
		private static Dictionary<Type, IEntityFactory2> _factoryPerType = new Dictionary<Type, IEntityFactory2>();

		/// <summary>Initializes the <see cref="EntityFactoryFactory"/> class.</summary>
		static EntityFactoryFactory()
		{
			foreach(int entityTypeValue in Enum.GetValues(typeof(RoomManagerment.Identity.EntityType)))
			{
				var factory = GetFactory((RoomManagerment.Identity.EntityType)entityTypeValue);
				_factoryPerType.Add(factory.ForEntityType ?? factory.Create().GetType(), factory);
			}
		}

		/// <summary>Gets the factory of the entity with the .NET type specified</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>factory to use or null if not found</returns>
		public static IEntityFactory2 GetFactory(Type typeOfEntity) { return _factoryPerType.GetValue(typeOfEntity); }

		/// <summary>Gets the factory of the entity with the RoomManagerment.Identity.EntityType specified</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>factory to use or null if not found</returns>
		public static IEntityFactory2 GetFactory(RoomManagerment.Identity.EntityType typeOfEntity)
		{
			switch(typeOfEntity)
			{
				case RoomManagerment.Identity.EntityType.PermissionEntity:
					return new PermissionEntityFactory();
				case RoomManagerment.Identity.EntityType.RefreshTokenEntity:
					return new RefreshTokenEntityFactory();
				case RoomManagerment.Identity.EntityType.RoleEntity:
					return new RoleEntityFactory();
				case RoomManagerment.Identity.EntityType.RolePermissionEntity:
					return new RolePermissionEntityFactory();
				case RoomManagerment.Identity.EntityType.UserEntity:
					return new UserEntityFactory();
				case RoomManagerment.Identity.EntityType.UserPermissionEntity:
					return new UserPermissionEntityFactory();
				case RoomManagerment.Identity.EntityType.UserProfileEntity:
					return new UserProfileEntityFactory();
				case RoomManagerment.Identity.EntityType.UserRoleEntity:
					return new UserRoleEntityFactory();
				case RoomManagerment.Identity.EntityType.MenuEntity:
					return new MenuEntityFactory();
				case RoomManagerment.Identity.EntityType.MenuPermissionEntity:
					return new MenuPermissionEntityFactory();
				case RoomManagerment.Identity.EntityType.UserMenuOverrideEntity:
					return new UserMenuOverrideEntityFactory();
				default:
					return null;
			}
		}
	}
		
	/// <summary>Element creator for creating project elements from somewhere else, like inside Linq providers.</summary>
	public class ElementCreator : ElementCreatorBase, IElementCreator2
	{
		/// <summary>Gets the factory of the Entity type with the RoomManagerment.Identity.EntityType value passed in</summary>
		/// <param name="entityTypeValue">The entity type value.</param>
		/// <returns>the entity factory of the entity type or null if not found</returns>
		public IEntityFactory2 GetFactory(int entityTypeValue) { return (IEntityFactory2)this.GetFactoryImpl(entityTypeValue); }
		
		/// <summary>Gets the factory of the Entity type with the .NET type passed in</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>the entity factory of the entity type or null if not found</returns>
		public IEntityFactory2 GetFactory(Type typeOfEntity) { return (IEntityFactory2)this.GetFactoryImpl(typeOfEntity); }

		/// <summary>Creates a new resultset fields object with the number of field slots reserved as specified</summary>
		/// <param name="numberOfFields">The number of fields.</param>
		/// <returns>ready to use resultsetfields object</returns>
		public IEntityFields2 CreateResultsetFields(int numberOfFields) { return new ResultsetFields(numberOfFields); }
		
		/// <inheritdoc/>
		public override IInheritanceInfoProvider ObtainInheritanceInfoProviderInstance() { return ModelInfoProviderSingleton.GetInstance(); }

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand) { return new DynamicRelation(leftOperand); }

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand, JoinHint joinType, DerivedTableDefinition rightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, rightOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(IEntityFieldCore leftOperand, JoinHint joinType, DerivedTableDefinition rightOperand, string aliasLeftOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, rightOperand, aliasLeftOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand, JoinHint joinType, string rightOperandEntityName, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, (RoomManagerment.Identity.EntityType)Enum.Parse(typeof(RoomManagerment.Identity.EntityType), rightOperandEntityName, false), aliasRightOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(string leftOperandEntityName, JoinHint joinType, string rightOperandEntityName, string aliasLeftOperand, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation((RoomManagerment.Identity.EntityType)Enum.Parse(typeof(RoomManagerment.Identity.EntityType), leftOperandEntityName, false), joinType, (RoomManagerment.Identity.EntityType)Enum.Parse(typeof(RoomManagerment.Identity.EntityType), rightOperandEntityName, false), aliasLeftOperand, aliasRightOperand, onClause);
		}
		
		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(IEntityFieldCore leftOperand, JoinHint joinType, string rightOperandEntityName, string aliasLeftOperand, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, (RoomManagerment.Identity.EntityType)Enum.Parse(typeof(RoomManagerment.Identity.EntityType), rightOperandEntityName, false), aliasLeftOperand, aliasRightOperand, onClause);
		}
		
		/// <inheritdoc/>
		protected override IEntityFactoryCore GetFactoryImpl(int entityTypeValue) { return EntityFactoryFactory.GetFactory((RoomManagerment.Identity.EntityType)entityTypeValue); }

		/// <inheritdoc/>
		protected override IEntityFactoryCore GetFactoryImpl(Type typeOfEntity) { return EntityFactoryFactory.GetFactory(typeOfEntity);	}

	}
}
