//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Auth.HelperClasses;
using RoomManagerment.Auth.FactoryClasses;
using RoomManagerment.Auth.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Auth.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Capability'.<br/><br/></summary>
	[Serializable]
	public partial class CapabilityEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static CapabilityEntityStaticMetaData _staticMetaData = new CapabilityEntityStaticMetaData();
		private static CapabilityRelations _relationsFactory = new CapabilityRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CapabilityEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CapabilityEntityStaticMetaData()
			{
				SetEntityCoreInfo("CapabilityEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Auth.EntityType.CapabilityEntity, typeof(CapabilityEntity), typeof(CapabilityEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static CapabilityEntity()
		{
		}

		/// <summary> CTor</summary>
		public CapabilityEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CapabilityEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CapabilityEntity</param>
		public CapabilityEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Capability which data should be fetched into this Capability object</param>
		public CapabilityEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Capability which data should be fetched into this Capability object</param>
		/// <param name="validator">The custom validator object for this CapabilityEntity</param>
		public CapabilityEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CapabilityEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CapabilityEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CapabilityRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Category property of the Entity Capability<br/><br/></summary>
		/// <remarks>Mapped on  table field: "capabilities"."category".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Category
		{
			get { return (System.String)GetValue((int)CapabilityFieldIndex.Category, true); }
			set { SetValue((int)CapabilityFieldIndex.Category, value); }
		}

		/// <summary>The CreatedAt property of the Entity Capability<br/><br/></summary>
		/// <remarks>Mapped on  table field: "capabilities"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)CapabilityFieldIndex.CreatedAt, true); }
			set { SetValue((int)CapabilityFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Description property of the Entity Capability<br/><br/></summary>
		/// <remarks>Mapped on  table field: "capabilities"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)CapabilityFieldIndex.Description, true); }
			set { SetValue((int)CapabilityFieldIndex.Description, value); }
		}

		/// <summary>The DisplayOrder property of the Entity Capability<br/><br/></summary>
		/// <remarks>Mapped on  table field: "capabilities"."display_order".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 DisplayOrder
		{
			get { return (System.Int32)GetValue((int)CapabilityFieldIndex.DisplayOrder, true); }
			set { SetValue((int)CapabilityFieldIndex.DisplayOrder, value); }
		}

		/// <summary>The Id property of the Entity Capability<br/><br/></summary>
		/// <remarks>Mapped on  table field: "capabilities"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)CapabilityFieldIndex.Id, true); }
			set { SetValue((int)CapabilityFieldIndex.Id, value); }
		}

		/// <summary>The KeyCode property of the Entity Capability<br/><br/></summary>
		/// <remarks>Mapped on  table field: "capabilities"."key_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String KeyCode
		{
			get { return (System.String)GetValue((int)CapabilityFieldIndex.KeyCode, true); }
			set { SetValue((int)CapabilityFieldIndex.KeyCode, value); }
		}

		/// <summary>The Name property of the Entity Capability<br/><br/></summary>
		/// <remarks>Mapped on  table field: "capabilities"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)CapabilityFieldIndex.Name, true); }
			set { SetValue((int)CapabilityFieldIndex.Name, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Capability<br/><br/></summary>
		/// <remarks>Mapped on  table field: "capabilities"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)CapabilityFieldIndex.UpdatedAt, false); }
			set { SetValue((int)CapabilityFieldIndex.UpdatedAt, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Auth
{
	public enum CapabilityFieldIndex
	{
		///<summary>Category. </summary>
		Category,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Description. </summary>
		Description,
		///<summary>DisplayOrder. </summary>
		DisplayOrder,
		///<summary>Id. </summary>
		Id,
		///<summary>KeyCode. </summary>
		KeyCode,
		///<summary>Name. </summary>
		Name,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Auth.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Capability. </summary>
	public partial class CapabilityRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCapabilityRelations
	{

		/// <summary>CTor</summary>
		static StaticCapabilityRelations() { }
	}
}
