//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Auth.HelperClasses;
using RoomManagerment.Auth.FactoryClasses;
using RoomManagerment.Auth.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Auth.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Role'.<br/><br/></summary>
	[Serializable]
	public partial class RoleEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static RoleEntityStaticMetaData _staticMetaData = new RoleEntityStaticMetaData();
		private static RoleRelations _relationsFactory = new RoleRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class RoleEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public RoleEntityStaticMetaData()
			{
				SetEntityCoreInfo("RoleEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Auth.EntityType.RoleEntity, typeof(RoleEntity), typeof(RoleEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static RoleEntity()
		{
		}

		/// <summary> CTor</summary>
		public RoleEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public RoleEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this RoleEntity</param>
		public RoleEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Role which data should be fetched into this Role object</param>
		public RoleEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Role which data should be fetched into this Role object</param>
		/// <param name="validator">The custom validator object for this RoleEntity</param>
		public RoleEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected RoleEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this RoleEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static RoleRelations Relations { get { return _relationsFactory; } }

		/// <summary>The CreatedAt property of the Entity Role<br/><br/></summary>
		/// <remarks>Mapped on  table field: "roles"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)RoleFieldIndex.CreatedAt, true); }
			set { SetValue((int)RoleFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Description property of the Entity Role<br/><br/></summary>
		/// <remarks>Mapped on  table field: "roles"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)RoleFieldIndex.Description, true); }
			set { SetValue((int)RoleFieldIndex.Description, value); }
		}

		/// <summary>The Id property of the Entity Role<br/><br/></summary>
		/// <remarks>Mapped on  table field: "roles"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)RoleFieldIndex.Id, true); }
			set { SetValue((int)RoleFieldIndex.Id, value); }
		}

		/// <summary>The KeyCode property of the Entity Role<br/><br/></summary>
		/// <remarks>Mapped on  table field: "roles"."key_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String KeyCode
		{
			get { return (System.String)GetValue((int)RoleFieldIndex.KeyCode, true); }
			set { SetValue((int)RoleFieldIndex.KeyCode, value); }
		}

		/// <summary>The Name property of the Entity Role<br/><br/></summary>
		/// <remarks>Mapped on  table field: "roles"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)RoleFieldIndex.Name, true); }
			set { SetValue((int)RoleFieldIndex.Name, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Role<br/><br/></summary>
		/// <remarks>Mapped on  table field: "roles"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)RoleFieldIndex.UpdatedAt, false); }
			set { SetValue((int)RoleFieldIndex.UpdatedAt, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Auth
{
	public enum RoleFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Description. </summary>
		Description,
		///<summary>Id. </summary>
		Id,
		///<summary>KeyCode. </summary>
		KeyCode,
		///<summary>Name. </summary>
		Name,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Auth.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Role. </summary>
	public partial class RoleRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticRoleRelations
	{

		/// <summary>CTor</summary>
		static StaticRoleRelations() { }
	}
}
