//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Auth.HelperClasses;
using RoomManagerment.Auth.FactoryClasses;
using RoomManagerment.Auth.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Auth.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Session'.<br/><br/></summary>
	[Serializable]
	public partial class SessionEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private UserEntity _user;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static SessionEntityStaticMetaData _staticMetaData = new SessionEntityStaticMetaData();
		private static SessionRelations _relationsFactory = new SessionRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SessionEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SessionEntityStaticMetaData()
			{
				SetEntityCoreInfo("SessionEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Auth.EntityType.SessionEntity, typeof(SessionEntity), typeof(SessionEntityFactory), false);
				AddNavigatorMetaData<SessionEntity, UserEntity>("User", "Sessions", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, RoomManagerment.Auth.RelationClasses.StaticSessionRelations.UserEntityUsingUserIdStatic, ()=>new SessionRelations().UserEntityUsingUserId, null, new int[] { (int)SessionFieldIndex.UserId }, null, true, (int)RoomManagerment.Auth.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static SessionEntity()
		{
		}

		/// <summary> CTor</summary>
		public SessionEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SessionEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SessionEntity</param>
		public SessionEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Session which data should be fetched into this Session object</param>
		public SessionEntity(System.String id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Session which data should be fetched into this Session object</param>
		/// <param name="validator">The custom validator object for this SessionEntity</param>
		public SessionEntity(System.String id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SessionEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SessionEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SessionRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The CreatedAt property of the Entity Session<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sessions"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)SessionFieldIndex.CreatedAt, true); }
			set { SetValue((int)SessionFieldIndex.CreatedAt, value); }
		}

		/// <summary>The ExpiresAt property of the Entity Session<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sessions"."expires_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> ExpiresAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SessionFieldIndex.ExpiresAt, false); }
			set { SetValue((int)SessionFieldIndex.ExpiresAt, value); }
		}

		/// <summary>The Id property of the Entity Session<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sessions"."id".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 128.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Id
		{
			get { return (System.String)GetValue((int)SessionFieldIndex.Id, true); }
			set { SetValue((int)SessionFieldIndex.Id, value); }
		}

		/// <summary>The IpAddress property of the Entity Session<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sessions"."ip_address".<br/>Table field type characteristics (type, precision, scale, length): Inet, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.Net.IPAddress IpAddress
		{
			get { return (System.Net.IPAddress)GetValue((int)SessionFieldIndex.IpAddress, true); }
			set { SetValue((int)SessionFieldIndex.IpAddress, value); }
		}

		/// <summary>The LastActivity property of the Entity Session<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sessions"."last_activity".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime LastActivity
		{
			get { return (System.DateTime)GetValue((int)SessionFieldIndex.LastActivity, true); }
			set { SetValue((int)SessionFieldIndex.LastActivity, value); }
		}

		/// <summary>The Payload property of the Entity Session<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sessions"."payload".<br/>Table field type characteristics (type, precision, scale, length): Jsonb, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Payload
		{
			get { return (System.String)GetValue((int)SessionFieldIndex.Payload, true); }
			set { SetValue((int)SessionFieldIndex.Payload, value); }
		}

		/// <summary>The UserAgent property of the Entity Session<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sessions"."user_agent".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String UserAgent
		{
			get { return (System.String)GetValue((int)SessionFieldIndex.UserAgent, true); }
			set { SetValue((int)SessionFieldIndex.UserAgent, value); }
		}

		/// <summary>The UserId property of the Entity Session<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sessions"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)SessionFieldIndex.UserId, true); }
			set { SetValue((int)SessionFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Auth
{
	public enum SessionFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>ExpiresAt. </summary>
		ExpiresAt,
		///<summary>Id. </summary>
		Id,
		///<summary>IpAddress. </summary>
		IpAddress,
		///<summary>LastActivity. </summary>
		LastActivity,
		///<summary>Payload. </summary>
		Payload,
		///<summary>UserAgent. </summary>
		UserAgent,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Auth.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Session. </summary>
	public partial class SessionRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between SessionEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Session.UserId - User.Id</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.Id, SessionFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSessionRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new SessionRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticSessionRelations() { }
	}
}
