//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Identity.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal partial class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitPermissionEntityMappings();
			InitRefreshTokenEntityMappings();
			InitRoleEntityMappings();
			InitRolePermissionEntityMappings();
			InitUserEntityMappings();
			InitUserPermissionEntityMappings();
			InitUserProfileEntityMappings();
			InitUserRoleEntityMappings();
			InitMenuEntityMappings();
			InitMenuPermissionEntityMappings();
			InitUserMenuOverrideEntityMappings();
		}

		/// <summary>Inits PermissionEntity's mappings</summary>
		private void InitPermissionEntityMappings()
		{
			this.AddElementMapping("PermissionEntity", @"room_managerment", @"auth", "permissions", 4, 0);
			this.AddElementFieldMapping("PermissionEntity", "Code", "code", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("PermissionEntity", "CreatedAt", "created_at", false, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("PermissionEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
			this.AddElementFieldMapping("PermissionEntity", "Name", "name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits RefreshTokenEntity's mappings</summary>
		private void InitRefreshTokenEntityMappings()
		{
			this.AddElementMapping("RefreshTokenEntity", @"room_managerment", @"auth", "refresh_tokens", 6, 0);
			this.AddElementFieldMapping("RefreshTokenEntity", "CreatedAt", "created_at", false, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("RefreshTokenEntity", "ExpiresAt", "expires_at", false, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("RefreshTokenEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
			this.AddElementFieldMapping("RefreshTokenEntity", "IsRevoked", "is_revoked", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 3);
			this.AddElementFieldMapping("RefreshTokenEntity", "Token", "token", false, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("RefreshTokenEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 5);
		}

		/// <summary>Inits RoleEntity's mappings</summary>
		private void InitRoleEntityMappings()
		{
			this.AddElementMapping("RoleEntity", @"room_managerment", @"auth", "roles", 4, 0);
			this.AddElementFieldMapping("RoleEntity", "Code", "code", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("RoleEntity", "CreatedAt", "created_at", false, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("RoleEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
			this.AddElementFieldMapping("RoleEntity", "Name", "name", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits RolePermissionEntity's mappings</summary>
		private void InitRolePermissionEntityMappings()
		{
			this.AddElementMapping("RolePermissionEntity", @"room_managerment", @"auth", "role_permissions", 2, 0);
			this.AddElementFieldMapping("RolePermissionEntity", "PermissionId", "permission_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RolePermissionEntity", "RoleId", "role_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"room_managerment", @"auth", "users", 7, 0);
			this.AddElementFieldMapping("UserEntity", "CreatedAt", "created_at", false, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("UserEntity", "Email", "email", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("UserEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
			this.AddElementFieldMapping("UserEntity", "PasswordHash", "password_hash", false, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("UserEntity", "Status", "status", false, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 4);
			this.AddElementFieldMapping("UserEntity", "UpdatedAt", "updated_at", true, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
			this.AddElementFieldMapping("UserEntity", "Username", "username", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 6);
		}

		/// <summary>Inits UserPermissionEntity's mappings</summary>
		private void InitUserPermissionEntityMappings()
		{
			this.AddElementMapping("UserPermissionEntity", @"room_managerment", @"auth", "user_permissions", 3, 0);
			this.AddElementFieldMapping("UserPermissionEntity", "IsGranted", "is_granted", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 0);
			this.AddElementFieldMapping("UserPermissionEntity", "PermissionId", "permission_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("UserPermissionEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
		}

		/// <summary>Inits UserProfileEntity's mappings</summary>
		private void InitUserProfileEntityMappings()
		{
			this.AddElementMapping("UserProfileEntity", @"room_managerment", @"auth", "user_profiles", 7, 0);
			this.AddElementFieldMapping("UserProfileEntity", "AvatarUrl", "avatar_url", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("UserProfileEntity", "CreatedAt", "created_at", false, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("UserProfileEntity", "FullName", "full_name", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("UserProfileEntity", "Phone", "phone", true, "Varchar", 30, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("UserProfileEntity", "SearchVector", "search_vector", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("UserProfileEntity", "UpdatedAt", "updated_at", true, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
			this.AddElementFieldMapping("UserProfileEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 6);
		}

		/// <summary>Inits UserRoleEntity's mappings</summary>
		private void InitUserRoleEntityMappings()
		{
			this.AddElementMapping("UserRoleEntity", @"room_managerment", @"auth", "user_roles", 2, 0);
			this.AddElementFieldMapping("UserRoleEntity", "RoleId", "role_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("UserRoleEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
		}

		/// <summary>Inits MenuEntity's mappings</summary>
		private void InitMenuEntityMappings()
		{
			this.AddElementMapping("MenuEntity", @"room_managerment", @"menu", "menus", 10, 0);
			this.AddElementFieldMapping("MenuEntity", "Code", "code", false, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("MenuEntity", "CreatedAt", "created_at", false, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("MenuEntity", "Icon", "icon", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("MenuEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
			this.AddElementFieldMapping("MenuEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 4);
			this.AddElementFieldMapping("MenuEntity", "Label", "label", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("MenuEntity", "OrderIndex", "order_index", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 6);
			this.AddElementFieldMapping("MenuEntity", "ParentId", "parent_id", true, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 7);
			this.AddElementFieldMapping("MenuEntity", "Path", "path", true, "Varchar", 300, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("MenuEntity", "UpdatedAt", "updated_at", true, "TimestampTz", 0, 0, 0, false, "", null, typeof(System.DateTime), 9);
		}

		/// <summary>Inits MenuPermissionEntity's mappings</summary>
		private void InitMenuPermissionEntityMappings()
		{
			this.AddElementMapping("MenuPermissionEntity", @"room_managerment", @"menu", "menu_permissions", 2, 0);
			this.AddElementFieldMapping("MenuPermissionEntity", "MenuId", "menu_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("MenuPermissionEntity", "PermissionCode", "permission_code", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits UserMenuOverrideEntity's mappings</summary>
		private void InitUserMenuOverrideEntityMappings()
		{
			this.AddElementMapping("UserMenuOverrideEntity", @"room_managerment", @"menu", "user_menu_overrides", 3, 0);
			this.AddElementFieldMapping("UserMenuOverrideEntity", "IsVisible", "is_visible", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 0);
			this.AddElementFieldMapping("UserMenuOverrideEntity", "MenuId", "menu_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("UserMenuOverrideEntity", "UserId", "user_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 2);
		}

	}
}
