//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Property.HelperClasses
{
	/// <summary>Field Creation Class for entity AmenityEntity</summary>
	public partial class AmenityFields
	{
		/// <summary>Creates a new AmenityEntity.Category field instance</summary>
		public static EntityField2 Category { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.Category); }}
		/// <summary>Creates a new AmenityEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.CreatedAt); }}
		/// <summary>Creates a new AmenityEntity.CreatedBy field instance</summary>
		public static EntityField2 CreatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.CreatedBy); }}
		/// <summary>Creates a new AmenityEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.DeletedAt); }}
		/// <summary>Creates a new AmenityEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.DeletedBy); }}
		/// <summary>Creates a new AmenityEntity.Icon field instance</summary>
		public static EntityField2 Icon { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.Icon); }}
		/// <summary>Creates a new AmenityEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.Id); }}
		/// <summary>Creates a new AmenityEntity.KeyCode field instance</summary>
		public static EntityField2 KeyCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.KeyCode); }}
		/// <summary>Creates a new AmenityEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.Name); }}
		/// <summary>Creates a new AmenityEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new AmenityEntity.UpdatedBy field instance</summary>
		public static EntityField2 UpdatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(AmenityFieldIndex.UpdatedBy); }}
	}

	/// <summary>Field Creation Class for entity DocumentEntity</summary>
	public partial class DocumentFields
	{
		/// <summary>Creates a new DocumentEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.CreatedAt); }}
		/// <summary>Creates a new DocumentEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.DeletedAt); }}
		/// <summary>Creates a new DocumentEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.DeletedBy); }}
		/// <summary>Creates a new DocumentEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.Description); }}
		/// <summary>Creates a new DocumentEntity.DocumentType field instance</summary>
		public static EntityField2 DocumentType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.DocumentType); }}
		/// <summary>Creates a new DocumentEntity.FileName field instance</summary>
		public static EntityField2 FileName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.FileName); }}
		/// <summary>Creates a new DocumentEntity.FileSize field instance</summary>
		public static EntityField2 FileSize { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.FileSize); }}
		/// <summary>Creates a new DocumentEntity.FileUrl field instance</summary>
		public static EntityField2 FileUrl { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.FileUrl); }}
		/// <summary>Creates a new DocumentEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.Id); }}
		/// <summary>Creates a new DocumentEntity.IsPrimary field instance</summary>
		public static EntityField2 IsPrimary { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.IsPrimary); }}
		/// <summary>Creates a new DocumentEntity.MimeType field instance</summary>
		public static EntityField2 MimeType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.MimeType); }}
		/// <summary>Creates a new DocumentEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.OrganizationId); }}
		/// <summary>Creates a new DocumentEntity.OwnerId field instance</summary>
		public static EntityField2 OwnerId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.OwnerId); }}
		/// <summary>Creates a new DocumentEntity.OwnerType field instance</summary>
		public static EntityField2 OwnerType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.OwnerType); }}
		/// <summary>Creates a new DocumentEntity.SortOrder field instance</summary>
		public static EntityField2 SortOrder { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.SortOrder); }}
		/// <summary>Creates a new DocumentEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new DocumentEntity.UploadedBy field instance</summary>
		public static EntityField2 UploadedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DocumentFieldIndex.UploadedBy); }}
	}

	/// <summary>Field Creation Class for entity MeterEntity</summary>
	public partial class MeterFields
	{
		/// <summary>Creates a new MeterEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.CreatedAt); }}
		/// <summary>Creates a new MeterEntity.CreatedBy field instance</summary>
		public static EntityField2 CreatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.CreatedBy); }}
		/// <summary>Creates a new MeterEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.DeletedAt); }}
		/// <summary>Creates a new MeterEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.DeletedBy); }}
		/// <summary>Creates a new MeterEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.Description); }}
		/// <summary>Creates a new MeterEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.Id); }}
		/// <summary>Creates a new MeterEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.IsActive); }}
		/// <summary>Creates a new MeterEntity.MeterNumber field instance</summary>
		public static EntityField2 MeterNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.MeterNumber); }}
		/// <summary>Creates a new MeterEntity.MeterType field instance</summary>
		public static EntityField2 MeterType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.MeterType); }}
		/// <summary>Creates a new MeterEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.OrganizationId); }}
		/// <summary>Creates a new MeterEntity.PropertyId field instance</summary>
		public static EntityField2 PropertyId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.PropertyId); }}
		/// <summary>Creates a new MeterEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.UnitId); }}
		/// <summary>Creates a new MeterEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new MeterEntity.UpdatedBy field instance</summary>
		public static EntityField2 UpdatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterFieldIndex.UpdatedBy); }}
	}

	/// <summary>Field Creation Class for entity MeterReadingEntity</summary>
	public partial class MeterReadingFields
	{
		/// <summary>Creates a new MeterReadingEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.CreatedAt); }}
		/// <summary>Creates a new MeterReadingEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.DeletedAt); }}
		/// <summary>Creates a new MeterReadingEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.DeletedBy); }}
		/// <summary>Creates a new MeterReadingEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.Id); }}
		/// <summary>Creates a new MeterReadingEntity.ImageUrl field instance</summary>
		public static EntityField2 ImageUrl { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.ImageUrl); }}
		/// <summary>Creates a new MeterReadingEntity.MeterId field instance</summary>
		public static EntityField2 MeterId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.MeterId); }}
		/// <summary>Creates a new MeterReadingEntity.Note field instance</summary>
		public static EntityField2 Note { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.Note); }}
		/// <summary>Creates a new MeterReadingEntity.ReadingDate field instance</summary>
		public static EntityField2 ReadingDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.ReadingDate); }}
		/// <summary>Creates a new MeterReadingEntity.TakenBy field instance</summary>
		public static EntityField2 TakenBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.TakenBy); }}
		/// <summary>Creates a new MeterReadingEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new MeterReadingEntity.Value field instance</summary>
		public static EntityField2 Value { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(MeterReadingFieldIndex.Value); }}
	}

	/// <summary>Field Creation Class for entity PropertiesUserEntity</summary>
	public partial class PropertiesUserFields
	{
		/// <summary>Creates a new PropertiesUserEntity.AssignedAt field instance</summary>
		public static EntityField2 AssignedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.AssignedAt); }}
		/// <summary>Creates a new PropertiesUserEntity.AssignedBy field instance</summary>
		public static EntityField2 AssignedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.AssignedBy); }}
		/// <summary>Creates a new PropertiesUserEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.CreatedAt); }}
		/// <summary>Creates a new PropertiesUserEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.DeletedAt); }}
		/// <summary>Creates a new PropertiesUserEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.DeletedBy); }}
		/// <summary>Creates a new PropertiesUserEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.Id); }}
		/// <summary>Creates a new PropertiesUserEntity.PropertyId field instance</summary>
		public static EntityField2 PropertyId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.PropertyId); }}
		/// <summary>Creates a new PropertiesUserEntity.RoleKey field instance</summary>
		public static EntityField2 RoleKey { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.RoleKey); }}
		/// <summary>Creates a new PropertiesUserEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new PropertiesUserEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertiesUserFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity PropertyEntity</summary>
	public partial class PropertyFields
	{
		/// <summary>Creates a new PropertyEntity.Address field instance</summary>
		public static EntityField2 Address { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Address); }}
		/// <summary>Creates a new PropertyEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Code); }}
		/// <summary>Creates a new PropertyEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.CreatedAt); }}
		/// <summary>Creates a new PropertyEntity.CreatedBy field instance</summary>
		public static EntityField2 CreatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.CreatedBy); }}
		/// <summary>Creates a new PropertyEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.DeletedAt); }}
		/// <summary>Creates a new PropertyEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.DeletedBy); }}
		/// <summary>Creates a new PropertyEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Description); }}
		/// <summary>Creates a new PropertyEntity.DistrictCode field instance</summary>
		public static EntityField2 DistrictCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.DistrictCode); }}
		/// <summary>Creates a new PropertyEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Id); }}
		/// <summary>Creates a new PropertyEntity.Latitude field instance</summary>
		public static EntityField2 Latitude { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Latitude); }}
		/// <summary>Creates a new PropertyEntity.Longitude field instance</summary>
		public static EntityField2 Longitude { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Longitude); }}
		/// <summary>Creates a new PropertyEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Name); }}
		/// <summary>Creates a new PropertyEntity.Notes field instance</summary>
		public static EntityField2 Notes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Notes); }}
		/// <summary>Creates a new PropertyEntity.NumberOfFloors field instance</summary>
		public static EntityField2 NumberOfFloors { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.NumberOfFloors); }}
		/// <summary>Creates a new PropertyEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.OrganizationId); }}
		/// <summary>Creates a new PropertyEntity.PropertyTypeId field instance</summary>
		public static EntityField2 PropertyTypeId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.PropertyTypeId); }}
		/// <summary>Creates a new PropertyEntity.ProvinceCode field instance</summary>
		public static EntityField2 ProvinceCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.ProvinceCode); }}
		/// <summary>Creates a new PropertyEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.Status); }}
		/// <summary>Creates a new PropertyEntity.StreetCode field instance</summary>
		public static EntityField2 StreetCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.StreetCode); }}
		/// <summary>Creates a new PropertyEntity.TotalUnits field instance</summary>
		public static EntityField2 TotalUnits { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.TotalUnits); }}
		/// <summary>Creates a new PropertyEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new PropertyEntity.UpdatedBy field instance</summary>
		public static EntityField2 UpdatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.UpdatedBy); }}
		/// <summary>Creates a new PropertyEntity.WardCode field instance</summary>
		public static EntityField2 WardCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyFieldIndex.WardCode); }}
	}

	/// <summary>Field Creation Class for entity PropertyTypeEntity</summary>
	public partial class PropertyTypeFields
	{
		/// <summary>Creates a new PropertyTypeEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.CreatedAt); }}
		/// <summary>Creates a new PropertyTypeEntity.CreatedBy field instance</summary>
		public static EntityField2 CreatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.CreatedBy); }}
		/// <summary>Creates a new PropertyTypeEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.DeletedAt); }}
		/// <summary>Creates a new PropertyTypeEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.DeletedBy); }}
		/// <summary>Creates a new PropertyTypeEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.Description); }}
		/// <summary>Creates a new PropertyTypeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.Id); }}
		/// <summary>Creates a new PropertyTypeEntity.KeyCode field instance</summary>
		public static EntityField2 KeyCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.KeyCode); }}
		/// <summary>Creates a new PropertyTypeEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.Name); }}
		/// <summary>Creates a new PropertyTypeEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.OrganizationId); }}
		/// <summary>Creates a new PropertyTypeEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new PropertyTypeEntity.UpdatedBy field instance</summary>
		public static EntityField2 UpdatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PropertyTypeFieldIndex.UpdatedBy); }}
	}

	/// <summary>Field Creation Class for entity TicketEntity</summary>
	public partial class TicketFields
	{
		/// <summary>Creates a new TicketEntity.AssignedTo field instance</summary>
		public static EntityField2 AssignedTo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.AssignedTo); }}
		/// <summary>Creates a new TicketEntity.CancelledAt field instance</summary>
		public static EntityField2 CancelledAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.CancelledAt); }}
		/// <summary>Creates a new TicketEntity.CancelledBy field instance</summary>
		public static EntityField2 CancelledBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.CancelledBy); }}
		/// <summary>Creates a new TicketEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.CreatedAt); }}
		/// <summary>Creates a new TicketEntity.CreatedBy field instance</summary>
		public static EntityField2 CreatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.CreatedBy); }}
		/// <summary>Creates a new TicketEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.DeletedAt); }}
		/// <summary>Creates a new TicketEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.DeletedBy); }}
		/// <summary>Creates a new TicketEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.Description); }}
		/// <summary>Creates a new TicketEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.Id); }}
		/// <summary>Creates a new TicketEntity.LeaseId field instance</summary>
		public static EntityField2 LeaseId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.LeaseId); }}
		/// <summary>Creates a new TicketEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.OrganizationId); }}
		/// <summary>Creates a new TicketEntity.PriorityId field instance</summary>
		public static EntityField2 PriorityId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.PriorityId); }}
		/// <summary>Creates a new TicketEntity.PropertyId field instance</summary>
		public static EntityField2 PropertyId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.PropertyId); }}
		/// <summary>Creates a new TicketEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.Status); }}
		/// <summary>Creates a new TicketEntity.Title field instance</summary>
		public static EntityField2 Title { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.Title); }}
		/// <summary>Creates a new TicketEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.UnitId); }}
		/// <summary>Creates a new TicketEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity TicketLogEntity</summary>
	public partial class TicketLogFields
	{
		/// <summary>Creates a new TicketLogEntity.Action field instance</summary>
		public static EntityField2 Action { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.Action); }}
		/// <summary>Creates a new TicketLogEntity.ActorId field instance</summary>
		public static EntityField2 ActorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.ActorId); }}
		/// <summary>Creates a new TicketLogEntity.ChargeTo field instance</summary>
		public static EntityField2 ChargeTo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.ChargeTo); }}
		/// <summary>Creates a new TicketLogEntity.CostAmount field instance</summary>
		public static EntityField2 CostAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.CostAmount); }}
		/// <summary>Creates a new TicketLogEntity.CostNote field instance</summary>
		public static EntityField2 CostNote { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.CostNote); }}
		/// <summary>Creates a new TicketLogEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.CreatedAt); }}
		/// <summary>Creates a new TicketLogEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.DeletedAt); }}
		/// <summary>Creates a new TicketLogEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.DeletedBy); }}
		/// <summary>Creates a new TicketLogEntity.Detail field instance</summary>
		public static EntityField2 Detail { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.Detail); }}
		/// <summary>Creates a new TicketLogEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.Id); }}
		/// <summary>Creates a new TicketLogEntity.LinkedInvoiceId field instance</summary>
		public static EntityField2 LinkedInvoiceId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.LinkedInvoiceId); }}
		/// <summary>Creates a new TicketLogEntity.TicketId field instance</summary>
		public static EntityField2 TicketId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.TicketId); }}
		/// <summary>Creates a new TicketLogEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new TicketLogEntity.VendorId field instance</summary>
		public static EntityField2 VendorId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.VendorId); }}
		/// <summary>Creates a new TicketLogEntity.WarrantyExpiresAt field instance</summary>
		public static EntityField2 WarrantyExpiresAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.WarrantyExpiresAt); }}
		/// <summary>Creates a new TicketLogEntity.WarrantyPeriodDays field instance</summary>
		public static EntityField2 WarrantyPeriodDays { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketLogFieldIndex.WarrantyPeriodDays); }}
	}

	/// <summary>Field Creation Class for entity TicketPriorityEntity</summary>
	public partial class TicketPriorityFields
	{
		/// <summary>Creates a new TicketPriorityEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketPriorityFieldIndex.CreatedAt); }}
		/// <summary>Creates a new TicketPriorityEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketPriorityFieldIndex.DeletedAt); }}
		/// <summary>Creates a new TicketPriorityEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketPriorityFieldIndex.Id); }}
		/// <summary>Creates a new TicketPriorityEntity.IsDefault field instance</summary>
		public static EntityField2 IsDefault { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketPriorityFieldIndex.IsDefault); }}
		/// <summary>Creates a new TicketPriorityEntity.KeyCode field instance</summary>
		public static EntityField2 KeyCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketPriorityFieldIndex.KeyCode); }}
		/// <summary>Creates a new TicketPriorityEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketPriorityFieldIndex.Name); }}
		/// <summary>Creates a new TicketPriorityEntity.SortOrder field instance</summary>
		public static EntityField2 SortOrder { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketPriorityFieldIndex.SortOrder); }}
		/// <summary>Creates a new TicketPriorityEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(TicketPriorityFieldIndex.UpdatedAt); }}
	}

	/// <summary>Field Creation Class for entity UnitEntity</summary>
	public partial class UnitFields
	{
		/// <summary>Creates a new UnitEntity.AreaM2 field instance</summary>
		public static EntityField2 AreaM2 { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.AreaM2); }}
		/// <summary>Creates a new UnitEntity.BaseRent field instance</summary>
		public static EntityField2 BaseRent { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.BaseRent); }}
		/// <summary>Creates a new UnitEntity.Code field instance</summary>
		public static EntityField2 Code { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.Code); }}
		/// <summary>Creates a new UnitEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.CreatedAt); }}
		/// <summary>Creates a new UnitEntity.CreatedBy field instance</summary>
		public static EntityField2 CreatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.CreatedBy); }}
		/// <summary>Creates a new UnitEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.DeletedAt); }}
		/// <summary>Creates a new UnitEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.DeletedBy); }}
		/// <summary>Creates a new UnitEntity.DepositAmount field instance</summary>
		public static EntityField2 DepositAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.DepositAmount); }}
		/// <summary>Creates a new UnitEntity.Floor field instance</summary>
		public static EntityField2 Floor { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.Floor); }}
		/// <summary>Creates a new UnitEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.Id); }}
		/// <summary>Creates a new UnitEntity.MaxOccupancy field instance</summary>
		public static EntityField2 MaxOccupancy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.MaxOccupancy); }}
		/// <summary>Creates a new UnitEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.Name); }}
		/// <summary>Creates a new UnitEntity.Note field instance</summary>
		public static EntityField2 Note { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.Note); }}
		/// <summary>Creates a new UnitEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.OrganizationId); }}
		/// <summary>Creates a new UnitEntity.PropertyId field instance</summary>
		public static EntityField2 PropertyId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.PropertyId); }}
		/// <summary>Creates a new UnitEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.Status); }}
		/// <summary>Creates a new UnitEntity.UnitType field instance</summary>
		public static EntityField2 UnitType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.UnitType); }}
		/// <summary>Creates a new UnitEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new UnitEntity.UpdatedBy field instance</summary>
		public static EntityField2 UpdatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitFieldIndex.UpdatedBy); }}
	}

	/// <summary>Field Creation Class for entity UnitAmenityEntity</summary>
	public partial class UnitAmenityFields
	{
		/// <summary>Creates a new UnitAmenityEntity.AmenityId field instance</summary>
		public static EntityField2 AmenityId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitAmenityFieldIndex.AmenityId); }}
		/// <summary>Creates a new UnitAmenityEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitAmenityFieldIndex.CreatedAt); }}
		/// <summary>Creates a new UnitAmenityEntity.CreatedBy field instance</summary>
		public static EntityField2 CreatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitAmenityFieldIndex.CreatedBy); }}
		/// <summary>Creates a new UnitAmenityEntity.UnitId field instance</summary>
		public static EntityField2 UnitId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(UnitAmenityFieldIndex.UnitId); }}
	}

	/// <summary>Field Creation Class for entity VendorEntity</summary>
	public partial class VendorFields
	{
		/// <summary>Creates a new VendorEntity.AccountHolderName field instance</summary>
		public static EntityField2 AccountHolderName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.AccountHolderName); }}
		/// <summary>Creates a new VendorEntity.AccountNumber field instance</summary>
		public static EntityField2 AccountNumber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.AccountNumber); }}
		/// <summary>Creates a new VendorEntity.Address field instance</summary>
		public static EntityField2 Address { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.Address); }}
		/// <summary>Creates a new VendorEntity.BranchName field instance</summary>
		public static EntityField2 BranchName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.BranchName); }}
		/// <summary>Creates a new VendorEntity.BusinessLicense field instance</summary>
		public static EntityField2 BusinessLicense { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.BusinessLicense); }}
		/// <summary>Creates a new VendorEntity.ContactEmail field instance</summary>
		public static EntityField2 ContactEmail { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.ContactEmail); }}
		/// <summary>Creates a new VendorEntity.ContactPerson field instance</summary>
		public static EntityField2 ContactPerson { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.ContactPerson); }}
		/// <summary>Creates a new VendorEntity.ContactPhone field instance</summary>
		public static EntityField2 ContactPhone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.ContactPhone); }}
		/// <summary>Creates a new VendorEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.CreatedAt); }}
		/// <summary>Creates a new VendorEntity.CreatedBy field instance</summary>
		public static EntityField2 CreatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.CreatedBy); }}
		/// <summary>Creates a new VendorEntity.DeletedAt field instance</summary>
		public static EntityField2 DeletedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.DeletedAt); }}
		/// <summary>Creates a new VendorEntity.DeletedBy field instance</summary>
		public static EntityField2 DeletedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.DeletedBy); }}
		/// <summary>Creates a new VendorEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.Email); }}
		/// <summary>Creates a new VendorEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.Id); }}
		/// <summary>Creates a new VendorEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.Name); }}
		/// <summary>Creates a new VendorEntity.OrganizationId field instance</summary>
		public static EntityField2 OrganizationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.OrganizationId); }}
		/// <summary>Creates a new VendorEntity.Phone field instance</summary>
		public static EntityField2 Phone { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.Phone); }}
		/// <summary>Creates a new VendorEntity.SepayBankId field instance</summary>
		public static EntityField2 SepayBankId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.SepayBankId); }}
		/// <summary>Creates a new VendorEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.Status); }}
		/// <summary>Creates a new VendorEntity.TaxCode field instance</summary>
		public static EntityField2 TaxCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.TaxCode); }}
		/// <summary>Creates a new VendorEntity.UpdatedAt field instance</summary>
		public static EntityField2 UpdatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.UpdatedAt); }}
		/// <summary>Creates a new VendorEntity.UpdatedBy field instance</summary>
		public static EntityField2 UpdatedBy { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.UpdatedBy); }}
		/// <summary>Creates a new VendorEntity.VendorType field instance</summary>
		public static EntityField2 VendorType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(VendorFieldIndex.VendorType); }}
	}
	

}