//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using RoomManagerment.Auth.EntityClasses;
using RoomManagerment.Auth.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace RoomManagerment.Auth.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the AuditLog entity</summary>
		public EntityQuery<AuditLogEntity> AuditLog { get { return Create<AuditLogEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Capability entity</summary>
		public EntityQuery<CapabilityEntity> Capability { get { return Create<CapabilityEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the EmailOtp entity</summary>
		public EntityQuery<EmailOtpEntity> EmailOtp { get { return Create<EmailOtpEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Role entity</summary>
		public EntityQuery<RoleEntity> Role { get { return Create<RoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Session entity</summary>
		public EntityQuery<SessionEntity> Session { get { return Create<SessionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the User entity</summary>
		public EntityQuery<UserEntity> User { get { return Create<UserEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserProfile entity</summary>
		public EntityQuery<UserProfileEntity> UserProfile { get { return Create<UserProfileEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}