//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using RoomManagerment.Organizations.FactoryClasses;
using RoomManagerment.Organizations.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Organizations.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitOrganizationEntityInfo();
			InitOrganizationBankingEntityInfo();
			InitOrganizationUserEntityInfo();
			InitOrganizationUserCapabilityEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits OrganizationEntity's info objects</summary>
		private void InitOrganizationEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrganizationFieldIndex), "OrganizationEntity");
			this.AddElementFieldInfo("OrganizationEntity", "Address", typeof(System.String), false, false, false, true,  (int)OrganizationFieldIndex.Address, 1073741824, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "Code", typeof(System.String), false, false, false, true,  (int)OrganizationFieldIndex.Code, 50, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrganizationFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "DeletedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationFieldIndex.DeletedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "DeletedBy", typeof(Nullable<System.Guid>), false, false, false, true,  (int)OrganizationFieldIndex.DeletedBy, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "Email", typeof(System.String), false, false, false, true,  (int)OrganizationFieldIndex.Email, 200, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "FirstTrialAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationFieldIndex.FirstTrialAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "HasEverPaid", typeof(System.Boolean), false, false, false, false,  (int)OrganizationFieldIndex.HasEverPaid, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)OrganizationFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "Mail", typeof(System.String), false, false, false, true,  (int)OrganizationFieldIndex.Mail, 200, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "Name", typeof(System.String), false, false, false, false,  (int)OrganizationFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "PaidSubscriptionsCount", typeof(System.Int32), false, false, false, false,  (int)OrganizationFieldIndex.PaidSubscriptionsCount, 0, 0, 10);
			this.AddElementFieldInfo("OrganizationEntity", "Phone", typeof(System.String), false, false, false, true,  (int)OrganizationFieldIndex.Phone, 50, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "Status", typeof(System.Int16), false, false, false, false,  (int)OrganizationFieldIndex.Status, 0, 0, 5);
			this.AddElementFieldInfo("OrganizationEntity", "TaxCode", typeof(System.String), false, false, false, true,  (int)OrganizationFieldIndex.TaxCode, 100, 0, 0);
			this.AddElementFieldInfo("OrganizationEntity", "UpdatedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationFieldIndex.UpdatedAt, 0, 0, 0);
		}

		/// <summary>Inits OrganizationBankingEntity's info objects</summary>
		private void InitOrganizationBankingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrganizationBankingFieldIndex), "OrganizationBankingEntity");
			this.AddElementFieldInfo("OrganizationBankingEntity", "AccountHolderName", typeof(System.String), false, false, false, false,  (int)OrganizationBankingFieldIndex.AccountHolderName, 200, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "AccountNumber", typeof(System.String), false, false, false, false,  (int)OrganizationBankingFieldIndex.AccountNumber, 50, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "BranchCode", typeof(System.String), false, false, false, true,  (int)OrganizationBankingFieldIndex.BranchCode, 50, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "BranchName", typeof(System.String), false, false, false, true,  (int)OrganizationBankingFieldIndex.BranchName, 200, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrganizationBankingFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "DeletedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationBankingFieldIndex.DeletedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "DeletedBy", typeof(Nullable<System.Guid>), false, false, false, true,  (int)OrganizationBankingFieldIndex.DeletedBy, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)OrganizationBankingFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "IsPrimary", typeof(System.Boolean), false, false, false, false,  (int)OrganizationBankingFieldIndex.IsPrimary, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "OrganizationId", typeof(System.Guid), false, true, false, false,  (int)OrganizationBankingFieldIndex.OrganizationId, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "SepayBankId", typeof(Nullable<System.Guid>), false, false, false, true,  (int)OrganizationBankingFieldIndex.SepayBankId, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "SwiftCode", typeof(System.String), false, false, false, true,  (int)OrganizationBankingFieldIndex.SwiftCode, 30, 0, 0);
			this.AddElementFieldInfo("OrganizationBankingEntity", "UpdatedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationBankingFieldIndex.UpdatedAt, 0, 0, 0);
		}

		/// <summary>Inits OrganizationUserEntity's info objects</summary>
		private void InitOrganizationUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrganizationUserFieldIndex), "OrganizationUserEntity");
			this.AddElementFieldInfo("OrganizationUserEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrganizationUserFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "DeletedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationUserFieldIndex.DeletedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "DeletedBy", typeof(Nullable<System.Guid>), false, false, false, true,  (int)OrganizationUserFieldIndex.DeletedBy, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)OrganizationUserFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "InvitationEmail", typeof(System.String), false, false, false, true,  (int)OrganizationUserFieldIndex.InvitationEmail, 200, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "InvitationExpiry", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationUserFieldIndex.InvitationExpiry, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "InvitationToken", typeof(System.String), false, false, false, true,  (int)OrganizationUserFieldIndex.InvitationToken, 200, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "InvitedByUserId", typeof(Nullable<System.Guid>), false, false, false, true,  (int)OrganizationUserFieldIndex.InvitedByUserId, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)OrganizationUserFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "LastActiveAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationUserFieldIndex.LastActiveAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "LastInactiveAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationUserFieldIndex.LastInactiveAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "OrganizationId", typeof(System.Guid), false, true, false, false,  (int)OrganizationUserFieldIndex.OrganizationId, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "RoleId", typeof(Nullable<System.Guid>), false, false, false, true,  (int)OrganizationUserFieldIndex.RoleId, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "UpdatedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationUserFieldIndex.UpdatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserEntity", "UserId", typeof(System.Guid), false, false, false, false,  (int)OrganizationUserFieldIndex.UserId, 0, 0, 0);
		}

		/// <summary>Inits OrganizationUserCapabilityEntity's info objects</summary>
		private void InitOrganizationUserCapabilityEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrganizationUserCapabilityFieldIndex), "OrganizationUserCapabilityEntity");
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "CapabilityId", typeof(System.Guid), false, false, false, false,  (int)OrganizationUserCapabilityFieldIndex.CapabilityId, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "CreatedAt", typeof(System.DateTime), false, false, false, false,  (int)OrganizationUserCapabilityFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "Granted", typeof(System.Boolean), false, false, false, false,  (int)OrganizationUserCapabilityFieldIndex.Granted, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "GrantedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationUserCapabilityFieldIndex.GrantedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "GrantedBy", typeof(Nullable<System.Guid>), false, false, false, true,  (int)OrganizationUserCapabilityFieldIndex.GrantedBy, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)OrganizationUserCapabilityFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "OrganizationUserId", typeof(System.Guid), false, true, false, false,  (int)OrganizationUserCapabilityFieldIndex.OrganizationUserId, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "RevokedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationUserCapabilityFieldIndex.RevokedAt, 0, 0, 0);
			this.AddElementFieldInfo("OrganizationUserCapabilityEntity", "UpdatedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OrganizationUserCapabilityFieldIndex.UpdatedAt, 0, 0, 0);
		}
	}
}