//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Property.HelperClasses;
using RoomManagerment.Property.FactoryClasses;
using RoomManagerment.Property.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Property.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Property'.<br/><br/></summary>
	[Serializable]
	public partial class PropertyEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<MeterEntity> _meters;
		private EntityCollection<PropertiesUserEntity> _propertiesUsers;
		private EntityCollection<TicketEntity> _tickets;
		private EntityCollection<UnitEntity> _units;
		private PropertyTypeEntity _propertyType;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static PropertyEntityStaticMetaData _staticMetaData = new PropertyEntityStaticMetaData();
		private static PropertyRelations _relationsFactory = new PropertyRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name PropertyType</summary>
			public static readonly string PropertyType = "PropertyType";
			/// <summary>Member name Meters</summary>
			public static readonly string Meters = "Meters";
			/// <summary>Member name PropertiesUsers</summary>
			public static readonly string PropertiesUsers = "PropertiesUsers";
			/// <summary>Member name Tickets</summary>
			public static readonly string Tickets = "Tickets";
			/// <summary>Member name Units</summary>
			public static readonly string Units = "Units";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PropertyEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PropertyEntityStaticMetaData()
			{
				SetEntityCoreInfo("PropertyEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Property.EntityType.PropertyEntity, typeof(PropertyEntity), typeof(PropertyEntityFactory), false);
				AddNavigatorMetaData<PropertyEntity, EntityCollection<MeterEntity>>("Meters", a => a._meters, (a, b) => a._meters = b, a => a.Meters, () => new PropertyRelations().MeterEntityUsingPropertyId, typeof(MeterEntity), (int)RoomManagerment.Property.EntityType.MeterEntity);
				AddNavigatorMetaData<PropertyEntity, EntityCollection<PropertiesUserEntity>>("PropertiesUsers", a => a._propertiesUsers, (a, b) => a._propertiesUsers = b, a => a.PropertiesUsers, () => new PropertyRelations().PropertiesUserEntityUsingPropertyId, typeof(PropertiesUserEntity), (int)RoomManagerment.Property.EntityType.PropertiesUserEntity);
				AddNavigatorMetaData<PropertyEntity, EntityCollection<TicketEntity>>("Tickets", a => a._tickets, (a, b) => a._tickets = b, a => a.Tickets, () => new PropertyRelations().TicketEntityUsingPropertyId, typeof(TicketEntity), (int)RoomManagerment.Property.EntityType.TicketEntity);
				AddNavigatorMetaData<PropertyEntity, EntityCollection<UnitEntity>>("Units", a => a._units, (a, b) => a._units = b, a => a.Units, () => new PropertyRelations().UnitEntityUsingPropertyId, typeof(UnitEntity), (int)RoomManagerment.Property.EntityType.UnitEntity);
				AddNavigatorMetaData<PropertyEntity, PropertyTypeEntity>("PropertyType", "Properties", (a, b) => a._propertyType = b, a => a._propertyType, (a, b) => a.PropertyType = b, RoomManagerment.Property.RelationClasses.StaticPropertyRelations.PropertyTypeEntityUsingPropertyTypeIdStatic, ()=>new PropertyRelations().PropertyTypeEntityUsingPropertyTypeId, null, new int[] { (int)PropertyFieldIndex.PropertyTypeId }, null, true, (int)RoomManagerment.Property.EntityType.PropertyTypeEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PropertyEntity()
		{
		}

		/// <summary> CTor</summary>
		public PropertyEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PropertyEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PropertyEntity</param>
		public PropertyEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Property which data should be fetched into this Property object</param>
		public PropertyEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Property which data should be fetched into this Property object</param>
		/// <param name="validator">The custom validator object for this PropertyEntity</param>
		public PropertyEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PropertyEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Meter' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoMeters() { return CreateRelationInfoForNavigator("Meters"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'PropertiesUser' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPropertiesUsers() { return CreateRelationInfoForNavigator("PropertiesUsers"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Ticket' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoTickets() { return CreateRelationInfoForNavigator("Tickets"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Unit' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUnits() { return CreateRelationInfoForNavigator("Units"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'PropertyType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPropertyType() { return CreateRelationInfoForNavigator("PropertyType"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PropertyEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PropertyRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Meter' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathMeters { get { return _staticMetaData.GetPrefetchPathElement("Meters", CommonEntityBase.CreateEntityCollection<MeterEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'PropertiesUser' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPropertiesUsers { get { return _staticMetaData.GetPrefetchPathElement("PropertiesUsers", CommonEntityBase.CreateEntityCollection<PropertiesUserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Ticket' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathTickets { get { return _staticMetaData.GetPrefetchPathElement("Tickets", CommonEntityBase.CreateEntityCollection<TicketEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Unit' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUnits { get { return _staticMetaData.GetPrefetchPathElement("Units", CommonEntityBase.CreateEntityCollection<UnitEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'PropertyType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPropertyType { get { return _staticMetaData.GetPrefetchPathElement("PropertyType", CommonEntityBase.CreateEntityCollection<PropertyTypeEntity>()); } }

		/// <summary>The Address property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."address".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Address
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.Address, true); }
			set { SetValue((int)PropertyFieldIndex.Address, value); }
		}

		/// <summary>The Code property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.Code, true); }
			set { SetValue((int)PropertyFieldIndex.Code, value); }
		}

		/// <summary>The CreatedAt property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)PropertyFieldIndex.CreatedAt, true); }
			set { SetValue((int)PropertyFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DeletedAt property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PropertyFieldIndex.DeletedAt, false); }
			set { SetValue((int)PropertyFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)PropertyFieldIndex.DeletedBy, false); }
			set { SetValue((int)PropertyFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Description property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.Description, true); }
			set { SetValue((int)PropertyFieldIndex.Description, value); }
		}

		/// <summary>The DistrictCode property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."district_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String DistrictCode
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.DistrictCode, true); }
			set { SetValue((int)PropertyFieldIndex.DistrictCode, value); }
		}

		/// <summary>The Id property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)PropertyFieldIndex.Id, true); }
			set { SetValue((int)PropertyFieldIndex.Id, value); }
		}

		/// <summary>The Latitude property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."latitude".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 7, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> Latitude
		{
			get { return (Nullable<System.Decimal>)GetValue((int)PropertyFieldIndex.Latitude, false); }
			set { SetValue((int)PropertyFieldIndex.Latitude, value); }
		}

		/// <summary>The Longitude property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."longitude".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 7, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> Longitude
		{
			get { return (Nullable<System.Decimal>)GetValue((int)PropertyFieldIndex.Longitude, false); }
			set { SetValue((int)PropertyFieldIndex.Longitude, value); }
		}

		/// <summary>The Name property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.Name, true); }
			set { SetValue((int)PropertyFieldIndex.Name, value); }
		}

		/// <summary>The Notes property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."notes".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Notes
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.Notes, true); }
			set { SetValue((int)PropertyFieldIndex.Notes, value); }
		}

		/// <summary>The NumberOfFloors property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."number_of_floors".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> NumberOfFloors
		{
			get { return (Nullable<System.Int32>)GetValue((int)PropertyFieldIndex.NumberOfFloors, false); }
			set { SetValue((int)PropertyFieldIndex.NumberOfFloors, value); }
		}

		/// <summary>The OrganizationId property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."organization_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid OrganizationId
		{
			get { return (System.Guid)GetValue((int)PropertyFieldIndex.OrganizationId, true); }
			set { SetValue((int)PropertyFieldIndex.OrganizationId, value); }
		}

		/// <summary>The PropertyTypeId property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."property_type_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> PropertyTypeId
		{
			get { return (Nullable<System.Guid>)GetValue((int)PropertyFieldIndex.PropertyTypeId, false); }
			set { SetValue((int)PropertyFieldIndex.PropertyTypeId, value); }
		}

		/// <summary>The ProvinceCode property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."province_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ProvinceCode
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.ProvinceCode, true); }
			set { SetValue((int)PropertyFieldIndex.ProvinceCode, value); }
		}

		/// <summary>The Status property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."status".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Status
		{
			get { return (System.Int16)GetValue((int)PropertyFieldIndex.Status, true); }
			set { SetValue((int)PropertyFieldIndex.Status, value); }
		}

		/// <summary>The StreetCode property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."street_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String StreetCode
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.StreetCode, true); }
			set { SetValue((int)PropertyFieldIndex.StreetCode, value); }
		}

		/// <summary>The TotalUnits property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."total_units".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 TotalUnits
		{
			get { return (System.Int32)GetValue((int)PropertyFieldIndex.TotalUnits, true); }
			set { SetValue((int)PropertyFieldIndex.TotalUnits, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PropertyFieldIndex.UpdatedAt, false); }
			set { SetValue((int)PropertyFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The WardCode property of the Entity Property<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties"."ward_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String WardCode
		{
			get { return (System.String)GetValue((int)PropertyFieldIndex.WardCode, true); }
			set { SetValue((int)PropertyFieldIndex.WardCode, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'MeterEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(MeterEntity))]
		public virtual EntityCollection<MeterEntity> Meters { get { return GetOrCreateEntityCollection<MeterEntity, MeterEntityFactory>("Property", true, false, ref _meters); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'PropertiesUserEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PropertiesUserEntity))]
		public virtual EntityCollection<PropertiesUserEntity> PropertiesUsers { get { return GetOrCreateEntityCollection<PropertiesUserEntity, PropertiesUserEntityFactory>("Property", true, false, ref _propertiesUsers); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'TicketEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(TicketEntity))]
		public virtual EntityCollection<TicketEntity> Tickets { get { return GetOrCreateEntityCollection<TicketEntity, TicketEntityFactory>("Property", true, false, ref _tickets); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'UnitEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(UnitEntity))]
		public virtual EntityCollection<UnitEntity> Units { get { return GetOrCreateEntityCollection<UnitEntity, UnitEntityFactory>("Property", true, false, ref _units); } }

		/// <summary>Gets / sets related entity of type 'PropertyTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PropertyTypeEntity PropertyType
		{
			get { return _propertyType; }
			set { SetSingleRelatedEntityNavigator(value, "PropertyType"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace RoomManagerment.Property
{
	public enum PropertyFieldIndex
	{
		///<summary>Address. </summary>
		Address,
		///<summary>Code. </summary>
		Code,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Description. </summary>
		Description,
		///<summary>DistrictCode. </summary>
		DistrictCode,
		///<summary>Id. </summary>
		Id,
		///<summary>Latitude. </summary>
		Latitude,
		///<summary>Longitude. </summary>
		Longitude,
		///<summary>Name. </summary>
		Name,
		///<summary>Notes. </summary>
		Notes,
		///<summary>NumberOfFloors. </summary>
		NumberOfFloors,
		///<summary>OrganizationId. </summary>
		OrganizationId,
		///<summary>PropertyTypeId. </summary>
		PropertyTypeId,
		///<summary>ProvinceCode. </summary>
		ProvinceCode,
		///<summary>Status. </summary>
		Status,
		///<summary>StreetCode. </summary>
		StreetCode,
		///<summary>TotalUnits. </summary>
		TotalUnits,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>WardCode. </summary>
		WardCode,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Property.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Property. </summary>
	public partial class PropertyRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between PropertyEntity and MeterEntity over the 1:n relation they have, using the relation between the fields: Property.Id - Meter.PropertyId</summary>
		public virtual IEntityRelation MeterEntityUsingPropertyId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Meters", true, new[] { PropertyFields.Id, MeterFields.PropertyId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PropertyEntity and PropertiesUserEntity over the 1:n relation they have, using the relation between the fields: Property.Id - PropertiesUser.PropertyId</summary>
		public virtual IEntityRelation PropertiesUserEntityUsingPropertyId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "PropertiesUsers", true, new[] { PropertyFields.Id, PropertiesUserFields.PropertyId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PropertyEntity and TicketEntity over the 1:n relation they have, using the relation between the fields: Property.Id - Ticket.PropertyId</summary>
		public virtual IEntityRelation TicketEntityUsingPropertyId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Tickets", true, new[] { PropertyFields.Id, TicketFields.PropertyId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PropertyEntity and UnitEntity over the 1:n relation they have, using the relation between the fields: Property.Id - Unit.PropertyId</summary>
		public virtual IEntityRelation UnitEntityUsingPropertyId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Units", true, new[] { PropertyFields.Id, UnitFields.PropertyId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PropertyEntity and PropertyTypeEntity over the m:1 relation they have, using the relation between the fields: Property.PropertyTypeId - PropertyType.Id</summary>
		public virtual IEntityRelation PropertyTypeEntityUsingPropertyTypeId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "PropertyType", false, new[] { PropertyTypeFields.Id, PropertyFields.PropertyTypeId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPropertyRelations
	{
		internal static readonly IEntityRelation MeterEntityUsingPropertyIdStatic = new PropertyRelations().MeterEntityUsingPropertyId;
		internal static readonly IEntityRelation PropertiesUserEntityUsingPropertyIdStatic = new PropertyRelations().PropertiesUserEntityUsingPropertyId;
		internal static readonly IEntityRelation TicketEntityUsingPropertyIdStatic = new PropertyRelations().TicketEntityUsingPropertyId;
		internal static readonly IEntityRelation UnitEntityUsingPropertyIdStatic = new PropertyRelations().UnitEntityUsingPropertyId;
		internal static readonly IEntityRelation PropertyTypeEntityUsingPropertyTypeIdStatic = new PropertyRelations().PropertyTypeEntityUsingPropertyTypeId;

		/// <summary>CTor</summary>
		static StaticPropertyRelations() { }
	}
}
