//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Property.HelperClasses;
using RoomManagerment.Property.FactoryClasses;
using RoomManagerment.Property.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Property.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'PropertiesUser'.<br/><br/></summary>
	[Serializable]
	public partial class PropertiesUserEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private PropertyEntity _property;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static PropertiesUserEntityStaticMetaData _staticMetaData = new PropertiesUserEntityStaticMetaData();
		private static PropertiesUserRelations _relationsFactory = new PropertiesUserRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Property</summary>
			public static readonly string Property = "Property";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PropertiesUserEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PropertiesUserEntityStaticMetaData()
			{
				SetEntityCoreInfo("PropertiesUserEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Property.EntityType.PropertiesUserEntity, typeof(PropertiesUserEntity), typeof(PropertiesUserEntityFactory), false);
				AddNavigatorMetaData<PropertiesUserEntity, PropertyEntity>("Property", "PropertiesUsers", (a, b) => a._property = b, a => a._property, (a, b) => a.Property = b, RoomManagerment.Property.RelationClasses.StaticPropertiesUserRelations.PropertyEntityUsingPropertyIdStatic, ()=>new PropertiesUserRelations().PropertyEntityUsingPropertyId, null, new int[] { (int)PropertiesUserFieldIndex.PropertyId }, null, true, (int)RoomManagerment.Property.EntityType.PropertyEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PropertiesUserEntity()
		{
		}

		/// <summary> CTor</summary>
		public PropertiesUserEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PropertiesUserEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PropertiesUserEntity</param>
		public PropertiesUserEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PropertiesUser which data should be fetched into this PropertiesUser object</param>
		public PropertiesUserEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PropertiesUser which data should be fetched into this PropertiesUser object</param>
		/// <param name="validator">The custom validator object for this PropertiesUserEntity</param>
		public PropertiesUserEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PropertiesUserEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Property' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProperty() { return CreateRelationInfoForNavigator("Property"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PropertiesUserEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PropertiesUserRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Property' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProperty { get { return _staticMetaData.GetPrefetchPathElement("Property", CommonEntityBase.CreateEntityCollection<PropertyEntity>()); } }

		/// <summary>The AssignedAt property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."assigned_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime AssignedAt
		{
			get { return (System.DateTime)GetValue((int)PropertiesUserFieldIndex.AssignedAt, true); }
			set { SetValue((int)PropertiesUserFieldIndex.AssignedAt, value); }
		}

		/// <summary>The AssignedBy property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."assigned_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> AssignedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)PropertiesUserFieldIndex.AssignedBy, false); }
			set { SetValue((int)PropertiesUserFieldIndex.AssignedBy, value); }
		}

		/// <summary>The CreatedAt property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)PropertiesUserFieldIndex.CreatedAt, true); }
			set { SetValue((int)PropertiesUserFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DeletedAt property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PropertiesUserFieldIndex.DeletedAt, false); }
			set { SetValue((int)PropertiesUserFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)PropertiesUserFieldIndex.DeletedBy, false); }
			set { SetValue((int)PropertiesUserFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Id property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)PropertiesUserFieldIndex.Id, true); }
			set { SetValue((int)PropertiesUserFieldIndex.Id, value); }
		}

		/// <summary>The PropertyId property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."property_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid PropertyId
		{
			get { return (System.Guid)GetValue((int)PropertiesUserFieldIndex.PropertyId, true); }
			set { SetValue((int)PropertiesUserFieldIndex.PropertyId, value); }
		}

		/// <summary>The RoleKey property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."role_key".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String RoleKey
		{
			get { return (System.String)GetValue((int)PropertiesUserFieldIndex.RoleKey, true); }
			set { SetValue((int)PropertiesUserFieldIndex.RoleKey, value); }
		}

		/// <summary>The UpdatedAt property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PropertiesUserFieldIndex.UpdatedAt, false); }
			set { SetValue((int)PropertiesUserFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserId property of the Entity PropertiesUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "properties_user"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)PropertiesUserFieldIndex.UserId, true); }
			set { SetValue((int)PropertiesUserFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'PropertyEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PropertyEntity Property
		{
			get { return _property; }
			set { SetSingleRelatedEntityNavigator(value, "Property"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace RoomManagerment.Property
{
	public enum PropertiesUserFieldIndex
	{
		///<summary>AssignedAt. </summary>
		AssignedAt,
		///<summary>AssignedBy. </summary>
		AssignedBy,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Id. </summary>
		Id,
		///<summary>PropertyId. </summary>
		PropertyId,
		///<summary>RoleKey. </summary>
		RoleKey,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Property.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: PropertiesUser. </summary>
	public partial class PropertiesUserRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between PropertiesUserEntity and PropertyEntity over the m:1 relation they have, using the relation between the fields: PropertiesUser.PropertyId - Property.Id</summary>
		public virtual IEntityRelation PropertyEntityUsingPropertyId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Property", false, new[] { PropertyFields.Id, PropertiesUserFields.PropertyId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPropertiesUserRelations
	{
		internal static readonly IEntityRelation PropertyEntityUsingPropertyIdStatic = new PropertiesUserRelations().PropertyEntityUsingPropertyId;

		/// <summary>CTor</summary>
		static StaticPropertiesUserRelations() { }
	}
}
