//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.13.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RoomManagerment.Property.HelperClasses;
using RoomManagerment.Property.FactoryClasses;
using RoomManagerment.Property.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RoomManagerment.Property.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'PropertyType'.<br/><br/></summary>
	[Serializable]
	public partial class PropertyTypeEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<PropertyEntity> _properties;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static PropertyTypeEntityStaticMetaData _staticMetaData = new PropertyTypeEntityStaticMetaData();
		private static PropertyTypeRelations _relationsFactory = new PropertyTypeRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Properties</summary>
			public static readonly string Properties = "Properties";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PropertyTypeEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PropertyTypeEntityStaticMetaData()
			{
				SetEntityCoreInfo("PropertyTypeEntity", InheritanceHierarchyType.None, false, (int)RoomManagerment.Property.EntityType.PropertyTypeEntity, typeof(PropertyTypeEntity), typeof(PropertyTypeEntityFactory), false);
				AddNavigatorMetaData<PropertyTypeEntity, EntityCollection<PropertyEntity>>("Properties", a => a._properties, (a, b) => a._properties = b, a => a.Properties, () => new PropertyTypeRelations().PropertyEntityUsingPropertyTypeId, typeof(PropertyEntity), (int)RoomManagerment.Property.EntityType.PropertyEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PropertyTypeEntity()
		{
		}

		/// <summary> CTor</summary>
		public PropertyTypeEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PropertyTypeEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PropertyTypeEntity</param>
		public PropertyTypeEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PropertyType which data should be fetched into this PropertyType object</param>
		public PropertyTypeEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for PropertyType which data should be fetched into this PropertyType object</param>
		/// <param name="validator">The custom validator object for this PropertyTypeEntity</param>
		public PropertyTypeEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PropertyTypeEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Property' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProperties() { return CreateRelationInfoForNavigator("Properties"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PropertyTypeEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PropertyTypeRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Property' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProperties { get { return _staticMetaData.GetPrefetchPathElement("Properties", CommonEntityBase.CreateEntityCollection<PropertyEntity>()); } }

		/// <summary>The CreatedAt property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)PropertyTypeFieldIndex.CreatedAt, true); }
			set { SetValue((int)PropertyTypeFieldIndex.CreatedAt, value); }
		}

		/// <summary>The CreatedBy property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."created_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> CreatedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)PropertyTypeFieldIndex.CreatedBy, false); }
			set { SetValue((int)PropertyTypeFieldIndex.CreatedBy, value); }
		}

		/// <summary>The DeletedAt property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."deleted_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeletedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PropertyTypeFieldIndex.DeletedAt, false); }
			set { SetValue((int)PropertyTypeFieldIndex.DeletedAt, value); }
		}

		/// <summary>The DeletedBy property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."deleted_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> DeletedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)PropertyTypeFieldIndex.DeletedBy, false); }
			set { SetValue((int)PropertyTypeFieldIndex.DeletedBy, value); }
		}

		/// <summary>The Description property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)PropertyTypeFieldIndex.Description, true); }
			set { SetValue((int)PropertyTypeFieldIndex.Description, value); }
		}

		/// <summary>The Id property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)PropertyTypeFieldIndex.Id, true); }
			set { SetValue((int)PropertyTypeFieldIndex.Id, value); }
		}

		/// <summary>The KeyCode property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."key_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String KeyCode
		{
			get { return (System.String)GetValue((int)PropertyTypeFieldIndex.KeyCode, true); }
			set { SetValue((int)PropertyTypeFieldIndex.KeyCode, value); }
		}

		/// <summary>The Name property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)PropertyTypeFieldIndex.Name, true); }
			set { SetValue((int)PropertyTypeFieldIndex.Name, value); }
		}

		/// <summary>The OrganizationId property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."organization_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> OrganizationId
		{
			get { return (Nullable<System.Guid>)GetValue((int)PropertyTypeFieldIndex.OrganizationId, false); }
			set { SetValue((int)PropertyTypeFieldIndex.OrganizationId, value); }
		}

		/// <summary>The UpdatedAt property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PropertyTypeFieldIndex.UpdatedAt, false); }
			set { SetValue((int)PropertyTypeFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UpdatedBy property of the Entity PropertyType<br/><br/></summary>
		/// <remarks>Mapped on  table field: "property_types"."updated_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UpdatedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)PropertyTypeFieldIndex.UpdatedBy, false); }
			set { SetValue((int)PropertyTypeFieldIndex.UpdatedBy, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'PropertyEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PropertyEntity))]
		public virtual EntityCollection<PropertyEntity> Properties { get { return GetOrCreateEntityCollection<PropertyEntity, PropertyEntityFactory>("PropertyType", true, false, ref _properties); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace RoomManagerment.Property
{
	public enum PropertyTypeFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>CreatedBy. </summary>
		CreatedBy,
		///<summary>DeletedAt. </summary>
		DeletedAt,
		///<summary>DeletedBy. </summary>
		DeletedBy,
		///<summary>Description. </summary>
		Description,
		///<summary>Id. </summary>
		Id,
		///<summary>KeyCode. </summary>
		KeyCode,
		///<summary>Name. </summary>
		Name,
		///<summary>OrganizationId. </summary>
		OrganizationId,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UpdatedBy. </summary>
		UpdatedBy,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RoomManagerment.Property.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: PropertyType. </summary>
	public partial class PropertyTypeRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between PropertyTypeEntity and PropertyEntity over the 1:n relation they have, using the relation between the fields: PropertyType.Id - Property.PropertyTypeId</summary>
		public virtual IEntityRelation PropertyEntityUsingPropertyTypeId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Properties", true, new[] { PropertyTypeFields.Id, PropertyFields.PropertyTypeId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPropertyTypeRelations
	{
		internal static readonly IEntityRelation PropertyEntityUsingPropertyTypeIdStatic = new PropertyTypeRelations().PropertyEntityUsingPropertyTypeId;

		/// <summary>CTor</summary>
		static StaticPropertyTypeRelations() { }
	}
}
